---
sidebar: sidebar 
permalink: concept-write-speed.html 
keywords: write speed, high write speed, normal write speed, nvfail, writing speed, ldm, low durability mode 
summary: Mit BlueXP können Sie normale oder hohe Schreibgeschwindigkeit für Cloud Volumes ONTAP auswählen. Bevor Sie sich für eine Schreibgeschwindigkeit entscheiden, sollten Sie die Unterschiede zwischen den normalen und hohen Einstellungen sowie Risiken und Empfehlungen verstehen, wenn Sie eine hohe Schreibgeschwindigkeit verwenden. 
---
= Schreibgeschwindigkeit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit BlueXP können Sie für die meisten Cloud Volumes ONTAP-Konfigurationen normale oder hohe Schreibgeschwindigkeit wählen. Bevor Sie sich für eine Schreibgeschwindigkeit entscheiden, sollten Sie die Unterschiede zwischen den normalen und hohen Einstellungen sowie Risiken und Empfehlungen verstehen, wenn Sie eine hohe Schreibgeschwindigkeit verwenden.



== Normale Schreibgeschwindigkeit

Wenn Sie die normale Schreibgeschwindigkeit wählen, werden die Daten direkt auf die Festplatte geschrieben. Wenn Daten direkt auf die Festplatte geschrieben werden, verringert sie die Wahrscheinlichkeit eines Datenverlusts bei einem ungeplanten Systemausfall oder bei einem kaskadierenden Ausfall eines ungeplanten Systemausfalls (nur HA-Paare).

Die normale Schreibgeschwindigkeit ist die Standardoption.



== Hohe Schreibgeschwindigkeit

Wenn Sie hohe Schreibgeschwindigkeit wählen, werden die Daten vor dem Schreiben auf die Festplatte im Speicher gepuffert, was eine schnellere Schreibleistung ermöglicht. Aufgrund dieses Cachings besteht die Gefahr eines Datenverlusts, wenn ein ungeplanter Systemausfall auftritt.

Die Datenmenge, die bei einem ungeplanten Systemausfall verloren gehen kann, entspricht der Spanne der letzten beiden Konsistenzpunkte. Ein Konsistenzpunkt ist das Schreiben gepufferter Daten auf die Festplatte. Ein Konsistenzpunkt tritt auf, wenn das Schreibprotokoll voll ist oder nach 10 Sekunden (je nachdem, was zuerst eintritt). Die Performance des vom Cloud-Provider bereitgestellten Storage kann sich jedoch auf die Dauer der Konsistenzpunktverarbeitung auswirken.



=== Wann wird hohe Schreibgeschwindigkeit verwendet

Eine hohe Schreibgeschwindigkeit ist eine gute Wahl, wenn eine hohe Schreib-Performance für Ihren Workload benötigt wird und Sie das Risiko eines Datenverlusts im Fall eines ungeplanten Systemausfalls standhalten oder einen kaskadierenden Ausfall im Zusammenhang mit einem ungeplanten Systemausfall (nur HA-Paare) auftreten können.



=== Empfehlungen bei hoher Schreibgeschwindigkeit

Wenn Sie eine hohe Schreibgeschwindigkeit aktivieren, sollten Sie den Schreibschutz auf Applikationsebene sicherstellen oder dass die Applikationen Datenverlust tolerieren können, falls diese auftreten.

ifdef::aws[]



=== Hohe Schreibgeschwindigkeit mit einem HA-Paar in AWS

Wenn Sie hohe Schreibgeschwindigkeit für ein HA-Paar in AWS aktivieren möchten, sollten Sie die Unterschiede bei der Sicherung zwischen einer Implementierung mit mehreren Verfügbarkeitszonen und einer Implementierung mit einer einzelnen Verfügbarkeitszone verstehen. Die Implementierung eines HA-Paars über mehrere Verfügbarkeitszonen hinweg sorgt für mehr Ausfallsicherheit und hilft, das Risiko eines Datenverlusts zu minimieren.

link:concept-ha.html["Erfahren Sie mehr über HA-Paare in AWS"].

endif::aws[]



=== Konfigurationen mit hoher Schreibgeschwindigkeit

Nicht alle Cloud Volumes ONTAP Konfigurationen unterstützen eine hohe Schreibgeschwindigkeit. Diese Konfigurationen verwenden standardmäßig normale Schreibgeschwindigkeit.

ifdef::aws[]



==== AWS

Wenn Sie ein Single-Node-System verwenden, unterstützt Cloud Volumes ONTAP bei allen Instanztypen eine hohe Schreibgeschwindigkeit.

Ab Version 9.8 unterstützt Cloud Volumes ONTAP bei fast allen unterstützten EC2-Instanztypen eine hohe Schreibgeschwindigkeit mit HA-Paaren, ausgenommen m5.xlarge und r5.xlarge.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Erfahren Sie mehr über die von Cloud Volumes ONTAP unterstützten Amazon EC2 Instanzen"^].

endif::aws[]

ifdef::azure[]



==== Azure

Wenn Sie ein Single-Node-System verwenden, unterstützt Cloud Volumes ONTAP für alle VM-Typen eine hohe Schreibgeschwindigkeit.

Wenn Sie ein HA-Paar verwenden, unterstützt Cloud Volumes ONTAP mit mehreren VM-Typen eine hohe Schreibgeschwindigkeit, beginnend mit Version 9.8. Wechseln Sie zum https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Versionshinweise zu Cloud Volumes ONTAP"^] Um die VM-Typen anzuzeigen, die eine hohe Schreibgeschwindigkeit unterstützen.

endif::azure[]

ifdef::gcp[]



==== Google Cloud

Wenn Sie ein Single-Node-System verwenden, unterstützt Cloud Volumes ONTAP bei allen Maschinentypen eine hohe Schreibgeschwindigkeit.

Wenn Sie ein HA-Paar verwenden, unterstützt Cloud Volumes ONTAP für mehrere VM-Typen, beginnend mit Version 9.13.0, eine hohe Schreibgeschwindigkeit. Wechseln Sie zum https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html#supported-configurations-by-license["Versionshinweise zu Cloud Volumes ONTAP"^] Um die VM-Typen anzuzeigen, die eine hohe Schreibgeschwindigkeit unterstützen.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Erfahren Sie mehr über die von Cloud Volumes ONTAP unterstützten Google Cloud-Maschinentypen"^].

endif::gcp[]



== So wählen Sie eine Schreibgeschwindigkeit aus

Sie können eine Schreibgeschwindigkeit wählen, wenn Sie eine neue Arbeitsumgebung erstellen und Sie können link:task-modify-write-speed.html["Ändern Sie die Schreibgeschwindigkeit für ein vorhandenes System"].



== Was bei einem Datenverlust zu erwarten ist

Wenn Datenverlust aufgrund hoher Schreibgeschwindigkeit auftritt, meldet das Event Management System (EMS) die folgenden beiden Ereignisse:

* Cloud Volumes ONTAP 9.12.1 oder höher
+
 NOTICE nv.data.loss.possible: An unexpected shutdown occurred while in high write speed mode, which possibly caused a loss of data.
* Cloud Volumes ONTAP 9.11.0 auf 9.11.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown with High Write Speed mode"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect..
* Cloud Volumes ONTAP 9.8 auf 9.10.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect.


Sollte dies der Fall sein, sollte Cloud Volumes ONTAP in der Lage sein, ohne Eingreifen des Benutzers weitere Daten bereitzustellen.



== So wird der Datenzugriff bei Datenverlust verhindert

Wenn Sie sich Sorgen um Datenverlust machen, möchten Sie, dass die Anwendungen bei Datenverlust nicht mehr ausgeführt werden und der Datenzugriff wieder aufgenommen wird, nachdem das Problem mit Datenverlust behoben wurde, können Sie die Option NVFAIL aus der CLI verwenden, um dieses Ziel zu erreichen.

Aktivieren der Option „NVFAIL“:: `vol modify -volume <vol-name> -nvfail on`
Zum Prüfen der NV-Fehler-Einstellungen:: `vol show -volume <vol-name> -fields nvfail`
Um die Option „NV-Fehler“ zu deaktivieren:: `vol modify -volume <vol-name> -nvfail off`


Wenn ein Datenverlust auftritt, sollte ein NFS- oder iSCSI-Volume mit aktiviertem NVFAIL die Bereitstellung von Daten beenden (es gibt keine Auswirkungen auf CIFS, was ein statusfreies Protokoll ist). Weitere Informationen finden Sie unter https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/GUID-40D04B8A-01F7-4E87-8161-E30BD80F5B7F.html["Auswirkungen von NV-Fehler auf den Zugriff auf NFS-Volumes oder LUNs"^].

Um den Status „NV-Fehler“ zu überprüfen:: `vol show -fields in-nvfailed-state`


Nachdem das Problem mit dem Datenverlust behoben wurde, können Sie den NV-Fehler-Status löschen und das Volume steht für den Datenzugriff zur Verfügung.

Zum Löschen des Status „NV-Fehler“:: `vol modify -volume <vol-name> -in-nvfailed-state false`

