---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: Sie können empfohlene Dashboards importieren, um bei der Beantwortung von Fragen zu Business Insight behilflich zu sein. 
keywords: dashboard, gallery, import 
---
= Import aus der Dashboard-Galerie
:allow-uri-read: 


[role="lead"]
Cloud Insights bietet verschiedene empfohlene Dashboards für geschäftliche Einblicke in Ihre Daten. Jedes Dashboard enthält Widgets, die dazu dienen, eine bestimmte Frage zu beantworten oder ein bestimmtes Problem zu lösen, das für die aktuell erfassten Daten in Ihrer Umgebung relevant ist.

So importieren Sie ein Dashboard aus der Galerie:

. Wählen Sie *Dashboard > Alle Dashboards anzeigen*
. Klicken Sie auf *+aus Galerie*
+
Es wird eine Liste von *Empfohlene Dashboards* angezeigt. Jedes Dashboard enthält eine bestimmte Frage, die Sie mithilfe des Dashboards lösen können. Dashboards bieten Unterstützung bei der Beantwortung von Fragen zu verschiedenen Objekttypen, wie AWS, NetApp, Storage, VMware, Und anderen

. Wählen Sie ein oder mehrere Dashboards aus der Liste aus und klicken Sie auf *Dashboards hinzufügen*. Diese Dashboards werden jetzt in Ihrer Dashboard-Liste angezeigt.


Zusätzlich zu den empfohlenen Dashboards können Sie auch *zusätzliche Dashboards* importieren, die für Ihre aktuellen Daten nicht relevant sind. Wenn Sie beispielsweise derzeit keine Speicherdatensammler installiert haben, aber zukünftig einige konfigurieren möchten, können Sie die speicherrelevanten Dashboards trotzdem importieren. Diese Dashboards sind zwar für die Anzeige verfügbar, zeigen jedoch möglicherweise keine relevanten Daten an, bis mindestens ein Speicherdatensammler konfiguriert ist.
