---
sidebar: sidebar 
permalink: concept_asset_page_overview.html 
summary: Asset-Seiten können für die meisten Objekttypen angezeigt werden. 
keywords: asset page, objects, landing page, Virtual machine, VM, Storage Virtual Machine, SVM, Volume, Internal volume, Host, Hypervisor, pool, Storage, Datastore, Application, node, Qtree, Disk, VMDK, Port, Switch, Fabric 
---
= Übersicht Über Die Asset-Seite
:allow-uri-read: 


[role="lead"]
Die Asset-Seiten fassen den aktuellen Status eines Assets zusammen und enthalten Links zu zusätzlichen Informationen über das Asset und die zugehörigen Assets.



== Arten von Asset-Seiten

Cloud Insights bietet Asset-Seiten für die folgenden Materialien:

* Virtual Machine
* Storage Virtual Machine (SVM)
* Datenmenge
* Internes Volumen
* Host (einschließlich Hypervisor)
* Storage-Pool
* Storage
* Datenspeicher
* Applikation
* Storage-Node
* Qtree
* Festplatte
* VMDK
* Port
* Switch
* Fabric




== Ändern des Zeitbereichs der angezeigten Daten

Standardmäßig werden auf einer Asset-Seite die letzten 24 Stunden an Daten angezeigt. Sie können jedoch das angezeigte Datensegment ändern, indem Sie einen anderen festen Zeitbereich oder einen benutzerdefinierten Zeitbereich auswählen, um immer weniger Daten anzuzeigen.

Sie können das Zeitsegment der angezeigten Daten ändern, indem Sie eine Option verwenden, die sich auf jeder Asset-Seite befindet, unabhängig vom Asset-Typ. Um den Zeitbereich zu ändern, klicken Sie in der oberen Leiste auf den angezeigten Zeitbereich, und wählen Sie zwischen den folgenden Zeitsegmenten aus:

* Letzte 15 Minuten
* Letzte 30 Minuten
* Letzte 60 Minuten
* Die Letzten 2 Stunden
* Die letzten 3 Stunden (dies ist die Standardeinstellung)
* Letzte 6 Stunden
* Letzte 12 Stunden
* Letzte 24 Stunden
* Letzte 2 Tage
* Letzte 3 Tage
* Letzte 7 Tage
* Letzte 30 Tage
* Benutzerdefinierter Zeitbereich


Im benutzerdefinierten Zeitbereich können Sie bis zu 31 aufeinander folgende Tage auswählen. Sie können für diesen Bereich auch die Startzeit und die Endzeit des Tages festlegen. Die standardmäßige Startzeit ist 12:00 UHR am ersten ausgewählten Tag und die standardmäßige Endzeit ist am letzten ausgewählten Tag 11:59 Uhr. Wenn Sie auf Anwenden klicken, wird der benutzerdefinierte Zeitbereich auf die Asset-Seite angewendet.



== Benutzerdefinierte Widgets Hinzufügen

Sie können Ihre eigenen Widgets zu jeder Asset-Seite hinzufügen. Widgets, die Sie hinzufügen, werden für alle Objekte dieses Typs auf den Asset-Seiten angezeigt. Wenn Sie beispielsweise ein benutzerdefiniertes Widget zu einer Speicherressource hinzufügen, wird dieses Widget auf den Asset-Seiten für alle Speicherressourcen angezeigt.
