---
sidebar: sidebar 
permalink: concept_acquisition_unit_requirements.html 
summary: Der Server oder die VM, die Sie als Akquisitionseinheit verwenden, müssen die Mindestanforderungen erfüllen 
keywords: AU, acquisition unit, RAU, requirements, sizing 
---
= Anforderungen An Die Erfassungseinheit
:allow-uri-read: 


[role="lead"]
Sie müssen eine Acquisition Unit (AU) installieren, um Informationen aus Ihren Infrastrukturdatenkollektoren (Speicher, VM, Port, EC2 usw.) zu erhalten. Bevor Sie die Acquisition Unit installieren, sollten Sie sicherstellen, dass Ihre Umgebung den Anforderungen für Betriebssystem, CPU, Arbeitsspeicher und Festplattenspeicher entspricht.



=== Anforderungen

|===


| Komponente | Linux-Anforderungen Erfüllt | Windows Anforderungen 


| Betriebssystem | Ein Computer mit einer lizenzierten Version von einer der folgenden: * CentOS (64-Bit): 7.2 bis 7.9, 8.1 bis 8.4 * Debian (64-Bit): 9 und 10 * Oracle Enterprise Linux (64-Bit): 7.5 bis 7.9, 8.1 bis 8.4 * Red hat Enterprise Linux (64-Bit): 7.2 bis 7.9, 8.1 bis 8.4 * Ubuntu Server: 18.04 und 20.04 LTS auf diesem Computer sollte keine andere Software auf Anwendungsebene ausgeführt werden. Es wird ein dedizierter Server empfohlen. | Ein Computer mit einer lizenzierten Version von einem der folgenden: * Microsoft Windows 10 64-Bit * Microsoft Windows Server 2012 * Microsoft Windows Server 2012 R2 * Microsoft Windows Server 2016 * Microsoft Windows Server 2019 auf diesem Computer sollte keine andere Software auf Anwendungsebene ausgeführt werden. Es wird ein dedizierter Server empfohlen. 


| CPU | 2 CPU-Kerne | Gleich 


| Speicher | 8 GB RAM | Gleich 


| Verfügbarer Festplattenspeicher | 50 GB für Linux sollte auf diese Weise Speicherplatz zugewiesen werden: /Opt/netapp 10 GB /var/log/netapp 40 GB | 50 GB 


| Netzwerk | 100 Mbit/s /1 Gbit/s Ethernet-Verbindung, statische IP-Adresse, IP-Konnektivität zu allen FC-Geräten und einen erforderlichen Port zur Cloud Insights-Instanz (80 oder 443). | Gleich 


| Berechtigungen | Sudo-Berechtigungen auf dem Akquisitionsgruppenserver. /Tmp muss mit exec-Funktionen montiert werden. | Administratorberechtigungen auf dem Akquisitionsbereiches-Server 


| Virenscan |  | Während der Installation müssen Sie alle Virenscanner vollständig deaktivieren. Nach der Installation müssen die Pfade, die von der Software Acquisition Unit verwendet werden, vom Virenscan ausgeschlossen werden. 
|===


=== Zusätzliche Empfehlungen

* Für eine genaue Audit- und Datenberichterstattung wird dringend empfohlen, die Zeit auf dem Acquisition Unit-Rechner mit *Network Time Protocol (NTP)* oder *Simple Network Time Protocol (SNTP)* zu synchronisieren.




=== Bezüglich Der Größenanpassung

Sie können mit einer Cloud Insights Acquisition Unit mit nur 8 GB Speicher und 50 GB Festplattenspeicher beginnen. In größeren Umgebungen sollten Sie sich jedoch die folgenden Fragen stellen:

Vorteile:

* Mehr als 2500 virtuelle Maschinen oder 10 große (> 2 Nodes) ONTAP-Cluster, Symmetrix oder HDS/HPE VSP/XP-Arrays auf dieser Acquisition Unit ermitteln?
* 75 oder mehr Datensammler auf dieser Akquisitionseinheit bereitstellen?


Für jede „Ja“ Antwort oben empfiehlt es sich, 8 GB Arbeitsspeicher und 50 GB Festplattenspeicher zur AU hinzuzufügen. Wenn Sie also beispielsweise beide Fragen mit „Ja“ beantwortet haben, sollten Sie ein 24-GB-Speichersystem mit 150 GB oder mehr Festplattenspeicher implementieren. Unter Linux wird der Speicherplatz, der dem Protokollverzeichnis hinzugefügt werden soll, hinzugefügt.

Wenn Sie weitere Fragen zur Dimensionierung benötigen, wenden Sie sich an den NetApp Support.
