---
sidebar: sidebar 
permalink: concept-flash-cache.html 
keywords: cloud volumes ontap, flash cache, read-intensive, read, random, databases, email, file services, compression, performance, nvme 
summary: Einige Cloud Volumes ONTAP Konfigurationen umfassen lokalen NVMe-Storage, den Cloud Volumes ONTAP als Flash Cache nutzt, um die Performance zu steigern. 
---
= Flash Cache
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Einige Cloud Volumes ONTAP Konfigurationen umfassen lokalen NVMe-Storage, den Cloud Volumes ONTAP für bessere Performance als _Flash Cache_ verwendet.



== Was ist Flash Cache?

Flash Cache beschleunigt den Zugriff auf Daten durch intelligente Cache-Speicherung von kürzlich gelesenen Anwenderdaten und NetApp Metadaten in Echtzeit. Es bringt Vorteile bei Random Read-intensiven Workloads, einschließlich Datenbanken, E-Mail und File Services.



== Unterstützte Konfigurationen

Flash Cache wird mit spezifischen Cloud Volumes ONTAP Konfigurationen unterstützt. Zeigen Sie unterstützte Konfigurationen in an https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Versionshinweise zu Cloud Volumes ONTAP"^]



== Einschränkungen

* Die Komprimierung muss auf allen Volumes deaktiviert sein, um die Performance-Verbesserungen durch Flash Cache bis zu Cloud Volumes ONTAP 9.12.0 nutzen zu können. Wenn Sie auf Cloud Volumes ONTAP 9.12.1 implementieren oder ein Upgrade durchführen, müssen Sie die Komprimierung nicht deaktivieren.
+
Entscheiden Sie sich für keine Storage-Effizienz bei der Erstellung eines Volumes mit BlueXP, oder erstellen Sie ein Volume und dann http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Deaktivieren Sie die Datenkomprimierung über die CLI"^].

* Cloud Volumes ONTAP unterstützt das Neustarten des Cache nicht, wenn ein Neustart nach einem Neustart erfolgen soll.

