---
sidebar: sidebar 
permalink: concept_telegraf_display_options.html 
keywords: telegraf, data, display, 
summary: Optionen zur Anzeige von Telegraf-Daten 
---
= Neue Metriken
:allow-uri-read: 


[role="lead"]
Cloud Insights bietet verschiedene *transform*-Optionen für bestimmte Metriken in Widgets (insbesondere die Metriken "Custom" oder Integration Metrics, wie etwa von Kubernetes, ONTAP Advanced Data, Telegraf Plugins, etc.), so dass Sie die Daten auf eine Reihe von Möglichkeiten anzuzeigen. Beim Hinzufügen transformbarer Metriken zu einem Widget werden Sie mit einem Dropdown-Menü mit den folgenden Optionen zur Transformation angezeigt:

Keine:: Die Daten werden ohne Manipulation als IS angezeigt.
Preis:: Aktueller Wert geteilt durch den Zeitbereich seit der vorherigen Beobachtung.
Kumulativ:: Die Akkumulation der Summe der vorherigen Werte und des aktuellen Werts.
Delta:: Die Differenz zwischen dem vorhergehenden Beobachtungswert und dem aktuellen Wert.
Delta-Preis:: Delta-Wert geteilt durch den Zeitraum seit der vorherigen Beobachtung.
Kumulierter Betrag:: Kumulativer Wert geteilt durch den Zeitraum seit der vorherigen Beobachtung.


Beachten Sie, dass bei der Transformation von Metriken nicht die zugrunde liegenden Daten selbst, sondern nur die Art und Weise geändert werden, wie Daten angezeigt werden.
