---
sidebar: sidebar 
permalink: concept-active-iq.html 
keywords: autosupport, active iq, digital advisor, active iq digital advisor, telemetry 
summary: Die AutoSupport-Komponente von ONTAP erfasst Telemetrie und sendet diese zur Analyse. Active IQ Digital Advisor analysiert die Daten von AutoSupport und bietet proaktive Betreuung und Optimierung. Mithilfe künstlicher Intelligenz erkennt Active IQ potenzielle Probleme und löst sie, bevor sie sich auf das Geschäft auswirken. 
---
= AutoSupport und Active IQ Digital Advisor
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die AutoSupport-Komponente von ONTAP erfasst Telemetrie und sendet diese zur Analyse. Active IQ Digital Advisor analysiert die Daten von AutoSupport und bietet proaktive Betreuung und Optimierung. Mithilfe künstlicher Intelligenz erkennt Active IQ potenzielle Probleme und löst sie, bevor sie sich auf das Geschäft auswirken. Änderung für Umstellungstest:

Änderung für die Lokalisierung.

Mit Active IQ optimieren Kunden ihre Dateninfrastruktur in der gesamten globalen Hybrid Cloud. Dazu bieten sie konkrete prädiktive Analysen und proaktiven Support über ein Cloud-basiertes Portal und eine mobile App. NetApp Kunden mit aktivem SupportEdge-Vertrag profitieren von Daten-fokussierten Einblicken und Empfehlungen von Active IQ (Funktionen variieren je nach Produkt- und Support-Tier).

Folgende Möglichkeiten bietet Active IQ:

* Planung von Upgrades:
+
Active IQ erkennt Probleme in Ihrer Umgebung, die durch ein Upgrade auf eine neuere Version von ONTAP behoben werden können, und die Upgrade Advisor Komponente unterstützt Sie bei der Planung eines erfolgreichen Upgrades.

* Sehen Sie sich das Wellness-System an.
+
Ihr Active IQ Dashboard meldet alle Probleme im Zusammenhang mit dem Wellness-Bereich und hilft Ihnen, diese Probleme zu beheben. Überwachen Sie die Systemkapazität, um sicherzugehen, dass nie mehr Speicherplatz belegt wird. Zeigen Sie Support-Cases für Ihr System an.

* Performance-Management:
+
Active IQ zeigt die System-Performance über einen längeren Zeitraum an, als Sie im ONTAP System Manager sehen können. Identifizieren Sie Konfigurations- und Systemprobleme, die Ihre Performance beeinträchtigen.
Maximale Effizienz Anzeige von Storage-Effizienz-Metriken und Identifizierung von Möglichkeiten, mehr Daten auf weniger Speicherplatz zu speichern

* Anzeige von Inventar und Konfiguration
+
Active IQ zeigt vollständige Informationen zur Bestands- und Software- und Hardwarekonfiguration an. Prüfen Sie, wann die Serviceverträge ablaufen und verlängern Sie sie, um sicherzustellen, dass der Support weiterhin gewährleistet ist.



.Verwandte Informationen
* https://docs.netapp.com/us-en/active-iq/["NetApp Dokumentation: Active IQ Digital Advisor"^]
* https://aiq.netapp.com/custom-dashboard/search["Starten Sie Active IQ"^]
* https://www.netapp.com/us/services/support-edge.aspx["SupportEdge Services"^]

