---
sidebar: sidebar 
permalink: concept_cs_attack_simulator.html 
keywords: ransomware, simulation, simulator, restrict, attack 
summary: Mit einem Skript können Sie einen Ransomware-Angriff zum Testen oder zur Demonstration von Cloud Secure simulieren 
---
= Cloud Secure: Simulation eines Angriffs
:allow-uri-read: 


[role="lead"]
Sie können die Anweisungen auf dieser Seite verwenden, um einen Angriff zum Testen oder zur Demonstration von Cloud Secure mit dem mitgelieferten Cloud Secure Ransomware-Simulationsskript zu simulieren.



== Dinge zu beachten, bevor Sie beginnen

* Das Ransomware-Simulationsskript funktioniert nur auf Linux.
* Das Skript wird mit den Installationsdateien des Cloud Secure Agent bereitgestellt. Sie ist auf jedem Rechner verfügbar, auf dem ein Cloud Secure-Agent installiert ist.
* Sie können das Skript auf dem Cloud Secure-Agent-Rechner selbst ausführen; es ist nicht erforderlich, einen anderen Linux-Rechner vorzubereiten. Wenn Sie jedoch das Skript lieber auf einem anderen System ausführen möchten, kopieren Sie einfach das Skript und führen es dort aus.




== Mindestens 1,000 Beispieldateien haben

Dieses Skript sollte auf einer SVM mit einem Ordner ausgeführt werden, der Dateien verschlüsselt. Es wird empfohlen, mindestens 1,000 Dateien in diesem Ordner und allen Unterordnern zu haben. Die Dateien dürfen nicht leer sein. Erstellen Sie die Dateien nicht und verschlüsseln Sie sie mit demselben Benutzer. Cloud Secure erachtet dies als eine risikoarme Aktivität und erzeugt daher keine Warnmeldung (d. h., der gleiche Benutzer ändert die Dateien, die er gerade erstellt hat).

Siehe unten für Anweisungen zu link:#create-files-programmatically["Programmgesteuertes Erstellen nicht leerer Dateien"].



== Bereiten Sie das System vor

Zunächst das Zielvolumen auf die Maschine montieren. Sie können entweder ein NFS-Mount oder einen CIFS-Export mounten.

So mounten Sie den NFS-Export in Linux:

....
mount -t nfs -o vers=4.0 10.193.177.158:/svmvol1 /mntpt
mount -t nfs -o vers=4.0 Vserver data IP>:/nfsvol /destinationlinuxfolder
....
Mounten Sie NFS Version 4.1 nicht; es wird von FPolicy nicht unterstützt.

So mounten Sie CIFS in Linux:

 mount -t cifs //10.193.77.91/sharedfolderincluster /root/destinationfolder/ -o username=raisa
Richten Sie als Nächstes einen Data Collector ein:

. Konfigurieren Sie den Cloud Secure-Agent, falls er nicht bereits ausgeführt wurde.
. Konfigurieren Sie den SVM-Datensammler, falls noch nicht geschehen.




== Führen Sie das Skript Ransomware Simulator aus

. Melden Sie sich (ssh) beim Cloud Secure-Agent-Rechner an.
. Navigieren Sie zu: _/opt/netapp/cloudSecure/Agent/install_
. Rufen Sie das Simulator-Skript ohne Parameter auf, um die Verwendung zu sehen:
+
....
# pwd
/opt/netapp/cloudsecure/agent/install
# ./ransomware_simulator.sh
Error: Invalid directory  provided.
Usage: ./ransomware_simulator.sh [-e] [-d] [-i <input_directory>]
       -e to encrypt files (default)
       -d to restore files
       -i <input_directory> - Files under the directory to be encrypted
....
+
....
Encrypt command example: ./ransomware_simulator.sh -e -i /mnt/audit/reports/
Decrypt command example: ./ransomware_simulator.sh -d -i /mnt/audit/reports/
....




== Verschlüsseln Sie Ihre Testdateien

Um die Dateien zu verschlüsseln, führen Sie den folgenden Befehl aus:

....
# ./ransomware_simulator.sh -e -i /root/for/
Encryption key is saved in /opt/netapp/cloudsecure/cloudsecure-agent-1.251.0/install/encryption-key,
which can be used for restoring the files.
Encrypted /root/for/File000.txt
Encrypted /root/for/File001.txt
Encrypted /root/for/File002.txt
...
....


== Stellen Sie Dateien wieder her

Führen Sie zum Entschlüsseln den folgenden Befehl aus:

....
[root@scspa2527575001 install]# ./ransomware_simulator.sh -d -i /root/for/
File /root/for/File000.txt is restored.
File /root/for/File001.txt is restored.
File /root/for/File002.txt is restored.
...
....


== Führen Sie das Skript mehrmals aus

Nachdem ein Ransomware-Angriff für einen Benutzer generiert wurde, wechseln Sie zu einem anderen Benutzer, um einen zusätzlichen Angriff zu generieren. Cloud Secure erlernt das Benutzerverhalten und warnt bei wiederholten Ransomware-Angriffen innerhalb kurzer Zeit für denselben Benutzer.



== Dateien programmatisch erstellen

Bevor Sie die Dateien erstellen, müssen Sie zunächst die Verarbeitung des Datensammlers beenden. Führen Sie die folgenden Schritte aus, bevor Sie den Datensammler zum Agenten hinzufügen. Wenn Sie den Datensammler bereits hinzugefügt haben, bearbeiten Sie einfach den Datensammler, geben Sie ein ungültiges Kennwort ein und speichern Sie es. Dadurch wird der Datensammler vorübergehend in einen Fehlerzustand versetzt. HINWEIS: Achten Sie darauf, dass Sie das ursprüngliche Passwort beachten!

Bevor Sie die Simulation ausführen, müssen Sie zuerst Dateien hinzufügen, die verschlüsselt werden sollen. Sie können die zu verschlüsselenden Dateien entweder manuell in den Zielordner kopieren oder die Dateien mithilfe eines Skripts (siehe Beispiel unten) programmatisch erstellen. Kopieren Sie mindestens 1,000 Dateien, unabhängig von der verwendeten Methode.

Wenn Sie die Dateien programmatisch erstellen möchten, gehen Sie wie folgt vor:

. Melden Sie sich im Feld Agent an.
. Mounten Sie einen NFS-Export aus der SVM des Filers auf die Agent Maschine. CD in diesen Ordner.
. Erstellen Sie in diesem Ordner eine Datei mit dem Namen createfiles.sh
. Kopieren Sie die folgenden Zeilen in diese Datei.
+
....
for i in {000..1000}
do
   echo hello > "File${i}.txt"
done
echo 3 > /proc/sys/vm/drop_caches ; sync
....
. Speichern Sie die Datei.
. Stellen Sie sicher, dass Sie die Berechtigung für die Ausführung der Datei ausführen:
+
 chmod 777 ./createfiles.sh
. Ausführen des Skripts:
+
 ./createfiles.sh
+
Im aktuellen Ordner werden 1000 Dateien erstellt.

. Aktivieren Sie den Datensammler erneut
+
Wenn Sie den Datensammler in Schritt 1 deaktiviert haben, bearbeiten Sie den Datensammler, geben Sie das richtige Passwort ein, und speichern Sie es. Stellen Sie sicher, dass der Datensammler wieder in Betrieb ist.


