---
sidebar: sidebar 
permalink: forensic_user_overview.html 
keywords: Forensic, user, user, activity 
summary: Benutzerdetails über forensische Benutzer 
---
= Übersicht Über Forensische Benutzer
:allow-uri-read: 


Informationen zu jedem Benutzer finden Sie in der Benutzerübersicht. Verwenden Sie diese Ansichten, um Benutzereigenschaften, zugehörige Einheiten und aktuelle Aktivitäten zu verstehen.



== Benutzerprofil

Zu den Benutzerprofilinformationen gehören die Kontaktinformationen und der Standort des Benutzers. Das Profil enthält folgende Informationen:

* Name des Benutzers
* E-Mail-Adresse des Benutzers
* Benutzermanager
* Telefonkontakt für den Benutzer
* Standort des Benutzers




== Benutzerverhalten

Die Informationen zum Benutzerverhalten identifizieren aktuelle Aktivitäten und Vorgänge, die vom Benutzer durchgeführt werden. Zu diesen Informationen gehören:

* Aktuelle Aktivität
+
** Letzter Zugriffsort
** Aktivitätsdiagramm
** Meldungen




* Betrieb der letzten sieben Tage
+
** Anzahl an Operationen






== Intervall Aktualisieren

Die Benutzerliste wird alle 12 Stunden aktualisiert.



== Aufbewahrungsrichtlinie

Wenn die Benutzerliste nicht erneut aktualisiert wird, wird sie 13 Monate lang aufbewahrt. Nach 13 Monaten werden die Daten gelöscht. Wird die Cloud Secure-Umgebung gelöscht, werden alle der Umgebung zugeordneten Daten gelöscht.
