---
sidebar: sidebar 
permalink: task_getting_started_with_cloud_secure.html 
summary: Erste Schritte mit Cloud Secure 
keywords: invite, roles, data collector, agent 
---
= Erste Schritte mit Cloud Secure
:allow-uri-read: 


Nachdem Sie sich zum ersten Mal bei Cloud Secure angemeldet und sich in Ihrer Umgebung angemeldet haben, müssen Sie die Konfigurationsschritte abschließen, bevor Sie mit dem Erfassen und Analysieren der Datenzugriffsinformationen beginnen können.



== Installieren Sie einen Agenten

Ein Agent ist erforderlich, um Daten zu erfassen, die von Cloud Secure analysiert werden sollen. Sie installieren die Agent-Software auf einem Server oder einer VM in Ihrer Umgebung. Für mehrere Datensammler kann ein einzelner Agent verwendet werden.

* Siehe link:concept_cs_agent_requirements.html["Anforderungen An Den Agenten"] Und link:task_cs_add_agent.html["Agenteninstallation"] Um Ihren Agent zu installieren.




== Konfigurieren Sie Datensammler

Cloud Secure sammelt Daten von einem User Directory Collectors für Benutzerinformationen und sammelt Daten von Speichersystemen. Cloud Secure analysiert mithilfe der Daten den Benutzerzugriff auf Einheiten in den Storage-Systemen.

* Informationen zum Konfigurieren eines Benutzerverzeichnisanschlusses finden Sie unter: link:task_config_user_dir_connect.html["Konfiguration Des Benutzerverzeichnisses"]
* Informationen zum Konfigurieren eines Data Collectors finden Sie in der Dokumentation links im Menü für jeden spezifischen Data Collector.

