---
sidebar: sidebar 
permalink: io_density_nonroot.html 
keywords: notifications, annotations, queries, applications, 
summary: I/O-Dichte 
---
= Wenn Daten zur I/O-Dichte sichergestellt werden, werden nur interne Daten-Volumes beschrieben
:allow-uri-read: 


[role="lead"]
In NetApp Storage-Systemen enthält das Root-Aggregat das Root-Volume, das spezielle Verzeichnisse und Konfigurationsdateien für die Verwaltung und Steuerung des Storage-Systems enthält. Diese Operationen können zu einem großen Teil der Aktivität im Root-Aggregat führen. Wenn Sie Cloud Insights nach den Top 10 internen Volumes mit der höchsten I/O-Dichte abfragen, können Ihre Ergebnisse NetApp Root-Aggregate als Mitglieder der Top 10 enthalten.

Bei der Überwachung Ihrer Umgebung ist es wichtiger, zu ermitteln, welche internen Datenvolumen eine hohe I/O-Dichte erzeugen. Damit nur die Daten-Volumes präzise ermittelt werden können, müssen die internen NetApp Volumes von Anfragen isoliert werden, die zur Überwachung der I/O-Dichte erforderlich sind.

Dieser Leitfaden beschreibt, wie NetApp Root-Aggregate leicht identifiziert, von den Ergebnissen interner Volume-Abfragen isoliert und Regeln erstellt werden können, die beim Hinzufügen zum System neue NetApp Root-Aggregate ausschließen. Die folgenden Cloud Insights Funktionen sorgen dafür, dass die Berichte zur I/O-Dichte von internen Daten-Volumes abgeleitet werden.

* Es wird eine Abfrage erstellt, um alle NetApp Root-Aggregate zu identifizieren, die von Cloud Insights überwacht werden.
* Jedem NetApp Root-Aggregat wird eine Annotation zugewiesen.
* Es wird eine Annotation-Regel erstellt, um die NetApp Root-Aggregate auszuschließen.




== Erstellen einer Abfrage, um NetApp Root-Aggregate in Ihrer Umgebung zu identifizieren

Abfragen ermöglichen die Suche auf granularer Ebene, basierend auf vom Benutzer ausgewählten Kriterien. Mit einer Abfrage können Sie nach internen Volumes in Ihrer Umgebung suchen, die das NetApp Root-Aggregat enthalten.

.Schritte
. Erstellen Sie in Cloud Insights eine Abfrage, um NetApp Root-Aggregate in Ihrer Umgebung zu identifizieren: *Abfragen > +neue Abfrage > Storage Pool*
. Geben Sie den Namen für das Root-Aggregat ein
+
Dieses Beispiel verwendet für den Namen „aggr0“. Beim Erstellen eines Aggregats müssen nur die folgenden Anforderungen für den Namen erfüllt werden:

+
** Er muss entweder mit einem Buchstaben oder einem Unterstrich (_) beginnen.
** Er darf nur Buchstaben, Ziffern und Unterstriche enthalten.
** Sie kann maximal 250 Zeichen umfassen.




In den meisten Fällen ist das Aggregat der Name aggr0, aggr_0, oder etwas ähnliches. Es könnte einen iterativen Prozess erfordern, um alle NetApp Root-Aggregate in Ihrer Umgebung zu identifizieren.

. Klicken Sie auf *Speichern* und geben Sie einen Namen für die neue Abfrage ein.
+
Wie bereits erwähnt, könnte dies ein iterativer Prozess sein und mehrere Anfragen zur Identifizierung aller NetApp Root-Aggregate erfordern.





== Erstellen Sie eine Anmerkung für die von Ihren Abfragen zurückgegebenen Root-Volumes

Anmerkungen sind spezielle Notizen, die Sie Ihren Assets zuweisen, damit Sie Assets nach ihren Anmerkungen filtern können. Die von Ihnen erstellten Annotationen werden verwendet, um die NetApp Root-Aggregate in Ihrer Umgebung zu identifizieren und sicherzustellen, dass diese nicht in einer Liste der internen Volumes mit der höchsten I/O-Dichte enthalten sind.

.Bevor Sie beginnen
Sie müssen alle Root-Aggregate identifiziert haben, die Sie aus dem Bericht „hohe I/O-Dichte“ ausschließen möchten.

.Schritte
. Erstellen Sie eine Annotation, um alle NetApp Root-Aggregate zu verknüpfen, die Sie mit Anfragen identifiziert haben: *Verwalten > Anmerkungen*
+
.. Geben Sie den Namen für die Anmerkung ein: *RootAggr*
.. Geben Sie eine Beschreibung der Anmerkung ein: *Root-Aggregat aus der Liste "hohe I/O-Dichte" entfernen*
.. Geben Sie den Typ der Anmerkung ein: *Boolean*


. Klicken Sie Auf *Speichern*




== Erstellen einer Annotation-Regel, um bestimmte Aggregate aus Ihrem I/O-Dichtebericht zu automatisieren

Alternativ zum manuellen Anwenden von Anmerkungen auf einzelne Assets können Sie mithilfe von Anmerkungsregeln automatisch Anmerkungen auf mehrere Assets anwenden. Anmerkungsregeln basieren auf Abfragen, die Sie erstellen, und wenn sie auf dem System ausgeführt werden, fügen sie vorhandenen Assets neue Assets hinzu. Wenn diese Vermögenswerte von der Einbeziehung ausgeschlossen werden, werden auch die neuen Vermögenswerte automatisch ausgeschlossen.

.Bevor Sie beginnen
Sie müssen eine Abfrage erstellt und gespeichert haben, die die NetApp Root-Aggregate identifiziert, die Sie in Ihrer Umgebung identifiziert haben.

.Schritte
. Klicken Sie im Menü Cloud Insights auf *Verwalten > Anmerkungen*
. Klicken Sie Auf *Hinzufügen*
. Gehen Sie wie folgt vor:
+
.. Geben Sie im Feld Name einen eindeutigen Namen ein, der die Regel beschreibt: *RootAggrExclude*
.. Klicken Sie auf Abfrage und wählen Sie die Abfrage aus, die Cloud Insights verwenden soll, um die Anmerkungsregel auf: *Aggregate0* anzuwenden
.. Klicken Sie auf Anmerkung und wählen Sie: *Root agg exclude*
.. Klicken Sie auf *Wert* und geben Sie *true* ein



