---
settings:
  name: Cloud Insights
  rss_page: concept_whats_new.html
  noindex: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr
sidebar:
  entries:
  - title: Cloud Insights-Dokumentation
    url: "/index.html"
  - title: Was ist neu
    url: "/concept_whats_new.html"
  - title: Anmeldung bei Cloud Insights
    url: "/task_cloud_insights_onboarding_1.html"
  - title: Sicherheit
    entries:
    - title: Sicherheitspraktiken
      url: "/security_overview.html"
    - title: Was wir speichern und wo
      url: "/security_information_and_region.html"
  - title: Erste Schritte
    entries:
    - title: Lernprogramme Zu Funktionen
      url: "/concept_feature_tutorials.html"
    - title: Daten Werden Erfasst
      entries:
      - title: Überblick
        url: "/task_getting_started_with_cloud_insights.html"
      - title: Anforderungen An Die Erfassungseinheit
        url: "/concept_acquisition_unit_requirements.html"
      - title: Konfigurieren einer Akquisitionseinheit
        url: "/task_configure_acquisition_unit.html"
      - title: Konfigurieren eines Agenten
        url: "/task_config_telegraf_agent.html"
      - title: Konfigurieren Von Datensammlern
        url: "/task_configure_data_collectors.html"
      - title: Bestimmen Des Erfassungsstatus Des Data Collectors
        url: "/concept_determining_data_collector_acq_status.html"
      - title: Konfigurierte Datensammler Verwalten
        url: "/task_view_configured_data_collectors.html"
      - title: Untersuchen Sie Fehler der Datensammlung
        url: "/task_research_failed_collector.html"
    - title: Empfohlene Dashboards Werden Importiert
      url: "/concept_import_from_dashboard_gallery.html"
    - title: Benutzerkonten und Rollen
      url: "/concept_user_roles.html"
    - title: Wechsel zu anderen Cloud Central Produkten
      url: "/concept_other_cloud_products.html"
  - title: Liste Des Data Collectors
    url: "/data_collector_list.html"
  - title: Abonnieren von Cloud Insights
    url: "/concept_subscribing_to_cloud_insights.html"
  - title: Automatische Geräteauflösung
    entries:
    - title: Übersicht Über Die Geräteauflösung
      url: "/concept_device_resolution_overview.html"
    - title: Regeln Zur Geräterauflösung
      url: "/task_device_resolution_rules.html"
    - title: Fibre Channel-Geräteauflösung
      url: "/task_device_resolution_fibre_channel.html"
    - title: IP-Geräteauflösung
      url: "/task_device_resolution_ip.html"
    - title: Einstellen Der Einstellungen Für Die Geräteauflösung
      url: "/task_device_resolution_preferences.html"
    - title: Beispiele für reguläre Ausdrücke
      url: "/concept_device_resolution_regex_examples.html"
  - title: Dashboards Werden Erstellt
    entries:
    - title: Dashboard-Übersicht
      url: "/concept_dashboards_overview.html"
    - title: Funktionen von Dashboards
      url: "/concept_dashboard_features.html"
    - title: Beispiele Für Dashboards
      entries:
      - title: Performance Von Virtual Machines
        url: "/task_dashboard_example_VM_performance.html"
    - title: Dashboard-Best Practices
      url: "/concept_dashboard_best_practices.html"
  - title: Kubernetes Explorer
    entries:
    - title: Kubernetes Übersichtsseite
      url: "/kubernetes_landing_page.html"
    - title: Kubernetes Cluster-Seite
      url: "/kubernetes_cluster_detail.html"
  - title: Arbeiten mit Abfragen
    entries:
    - title: Abfragen Von Assets
      url: "/concept_querying_assets.html"
    - title: Erstellen einer Abfrage
      url: "/task_create_query.html"
    - title: Anzeigen Verfügbarer Abfragen
      url: "/task_view_queries.html"
    - title: Abfrageergebnisse werden in .CSV exportiert
      url: "/task_export_query_results.html"
    - title: Eine Abfrage ändern oder löschen
      url: "/task_modify_delete_query.html"
    - title: Zuweisen mehrerer Anwendungen/Anmerkungen zu Objekten
      url: "/task_query_assign_multiple_applicationss.html"
    - title: Tabellenwerte werden in die Zwischenablage kopiert
      url: "/task_query_copy_table_values.html"
    - title: Abfragen Von Protokollen
      url: "/concept_log_explorer.html"
  - title: Arbeiten mit Anmerkungen
    entries:
    - title: Anmerkungen Definieren
      url: "/task_defining_annotations.html"
    - title: Verwenden Von Anmerkungen
      url: "/task_create_annotation.html"
    - title: Anmerkungsregeln Werden Verwendet
      url: "/task_create_annotation_rules.html"
    - title: Anmerkungen mit API importieren
      url: "/task_annotation_import.html"
  - title: Arbeiten mit Anwendungen
    entries:
    - title: Anwendungskonzepte
      url: "/concept_about_applications.html"
    - title: Anwendungen Werden Konfiguriert
      url: "/task_create_application.html"
  - title: Monitore und Alarme
    entries:
    - title: Erstellen Von Monitoren
      url: "/task_create_monitor.html"
    - title: Anzeigen und Verwalten von Warnungen
      url: "/task_view_and_manage_alerts.html"
    - title: Benachrichtigungsempfänger Werden Konfiguriert
      url: "/concept_notifications_email.html"
    - title: Systemdefinierte Monitore
      url: "/task_system_monitors.html"
  - title: Arbeiten mit APIs
    url: "/API_Overview.html"
  - title: Webhook-Benachrichtigung
    url: "/task_create_webhook.html"
  - title: Monitoring Ihrer Umgebung
    entries:
    - title: Auditing Von Ereignissen
      url: "/concept_audit.html"
    - title: TTL und Downsampling
      url: concept_ttl_and_downsampling.html
  - title: Informationen Zur Asset-Seite
    entries:
    - title: Übersicht Über Die Asset-Seite
      url: "/concept_asset_page_overview.html"
    - title: Kontextabhängige Filterung nach Objekten
      url: "/concept_in_context_filters.html"
    - title: Abschnitte Mit Zusammenfassung Der Topologie
      url: "/concept_asset_summary_section.html"
    - title: Abschnitt „Experten“
      url: "/concept_asset_expert_view_section.html"
    - title: Abschnitt „Benutzerdaten“
      url: "/concept_asset_user_data_section.html"
    - title: Abschnitt „Verwandte Warnmeldungen“
      url: "/concept_asset_alerts_section.html"
    - title: Tipps und Tricks für die Suche nach Ressourcen
      url: "/concept_searching_assets.html"
  - title: Berichterstellung
    entries:
    - title: Berichterstellung – Übersicht
      url: "/reporting_overview.html"
    - title: Benutzerrollen Melden
      url: "/reporting_user_roles.html"
    - title: Verwenden Von Vordefinierten Berichten
      url: "/reporting_predefined_reports.html"
    - title: Storage Manager Dashboard
      url: "/reporting_storage_manager_dashboard.html"
    - title: Erstellen eines Beispielberichts
      url: "/reporting_create_example.html"
    - title: Verwalten Von Berichten
      url: "/reporting_managing_reports.html"
    - title: Benutzerdefinierte Berichte
      url: "/reporting_creating_custom_reports.html"
    - title: Datenmodelle
      url: "/reporting_creating_custom_reports.html#reporting-data-models"
    - title: Reporting-Datenbank-API
      url: "/reporting_querying_database.html"
    - title: Datenhaltung
      url: "/reporting_data_retention.html"
    - title: Schemabdiagramme
      url: "/reporting_schema_diagrams.html"
    - title: Schematabellen
      url: "/reference_schemas.html"
  - title: Cloud Secure
    entries:
    - title: Informationen zu Cloud Secure
      url: "/cs_intro.html"
    - title: Erste Schritte
      entries:
      - title: Erste Schritte mit Cloud Secure
        url: "/task_cs_getting_started.html"
      - title: Anforderungen Für Cloud Secure-Agenten
        url: "/concept_cs_agent_requirements.html"
      - title: Konfigurieren eines Cloud Secure-Agenten
        url: "/task_cs_add_agent.html"
      - title: Löschen eines Cloud Secure-Agenten
        url: "/task_cs_delete_agent.html"
      - title: Konfigurieren eines AD Directory Collectors
        url: "/task_config_user_dir_connect.html"
      - title: Konfigurieren eines LDAP Directory Collectors
        url: "/task_config_user_dir_connect_ldap.html"
      - title: Konfiguration des Amazon FSX für NetApp ONTAP Collector
        url: "/task_config_cs_amazon_fsx.html"
      - title: Konfiguration des ONTAP SVM Data Collector
        url: "/task_add_collector_svm.html"
      - title: Konfigurieren des Cloud ONTAP Data Collectors
        url: "/task_config_cs_incloud.html"
      - title: Cloud Secure Benutzerverwaltung
        url: "/task_cs_user_management.html"
      - title: Ereignisprüfung
        url: "/concept_cs_event_rate_checker.html"
    - title: Meldungen
      url: "/cs_alert_data.html"
    - title: Forensik
      entries:
      - title: Vorgangsforensik - Alle Aktivitäten
        url: "/forensic_activity_history.html"
      - title: Vorgangsforensik - Einheiten
        url: "/forensic_entity_detail.html"
      - title: Benutzer
        url: "/forensic_user_overview.html"
    - title: Automatisierte Antwortrichtlinien
      url: "/cs_automated_response_policies.html"
    - title: Einschränken Des Benutzerzugriffs
      url: "/cs_restrict_user_access.html"
    - title: Simulation eines Angriffs gegen Ransomware
      url: "/concept_cs_attack_simulator.html"
    - title: Benachrichtigungen
      url: "/cs_notifications_email.html"
    - title: Cloud Secure API
      url: "/concept_cs_api.html"
  - title: Active IQ
    url: "/concept_activeiq.html"
  - title: Fehlerbehebung
    entries:
    - title: Allgemeine Fehlerbehebung
      url: "/task_troubleshooting_general_problems.html"
    - title: Fehlerbehebung Bei Problemen Mit Der Linux-Erfassungseinheit
      url: "/task_troubleshooting_linux_acquisition_unit_problems.html"
    - title: Fehlerbehebung Bei Problemen Mit Der Windows-Erfassungseinheit
      url: "/task_troubleshooting_windows_acquisition_unit_problems.html"
    - title: Daten-Collector-Fehler Werden Untersucht
      url: "/task_research_failed_collector.html"
  - title: Referenzsupport
    entries:
    - title: Support Wird Angefordert
      url: "/concept_requesting_support.html"
    - title: Data Collector Supportmatrix
      url: "/reference_data_collector_support_matrix.html"
    - title: Data Collector Reference - Infrastruktur
      entries:
      - title: Bieterreferenzübersicht
        url: "/concept_data_collector_reference.html"
      - title: AWS
        url: "/task_dc_amazon_ec2.html"
      - title: Azure
        url: "/task_dc_ms_azure.html"
      - title: Broadcom
        entries:
        - title: Brocade Network Advisor
          url: "/task_dc_brocade_bna.html"
        - title: Fibre Channel Switch
          url: "/task_dc_brocade_fc_switch.html"
      - title: Cisco
        url: "/task_dc_cisco_fc_switch.html"
      - title: Dell
        entries:
        - title: XC-Serie
          url: "/task_dc_dell_xc_series.html"
      - title: Dell EMC
        entries:
        - title: Data Domain
          url: "/task_dc_emc_datadomain.html"
        - title: ECS
          url: "/task_dc_emc_ecs.html"
        - title: PowerScale
          url: "/task_dc_emc_isilon.html"
        - title: PowerStore
          url: "/task_dc_emc_powerstore.html"
        - title: RecoverPoint
          url: "/task_dc_emc_recoverpoint.html"
        - title: ScaleIO
          url: "/task_dc_emc_scaleio.html"
        - title: Unity (VNXe)
          url: "/task_dc_emc_unity.html"
        - title: VMAX/PowerMax
          url: "/task_dc_emc_vmax_powermax.html"
        - title: VNX Block (CLARiiON)
          url: "/task_dc_emc_vnx_block.html"
        - title: VNX-Datei (Celerra)
          url: "/task_dc_emc_vnx_file.html"
        - title: VNX Unified
          url: "/task_dc_emc_vnx_unified.html"
        - title: VPLEX
          url: "/task_dc_emc_vplex.html"
        - title: XtremIO
          url: "/task_dc_emc_xio.html"
      - title: Fujitsu
        url: "/task_dc_fujitsu_eternus.html"
      - title: Google
        url: "/task_dc_google_cloud.html"
      - title: HP Enterprise
        entries:
        - title: HP Alletra 9000 und Primera
          url: "/task_dc_hp_3par.html"
        - title: HP Command View AE
          url: "/task_dc_hpe_commandview.html"
        - title: HPE Alletra 6000
          url: "/task_dc_hpe_nimble.html"
      - title: Hitachi Data Systems (Hds)
        entries:
        - title: HDS Command Suite
          url: "/task_dc_hds_commandsuite.html"
        - title: HDS HNAS
          url: "/task_dc_hds_nas.html"
        - title: HDS Ops Center
          url: "/task_dc_hds_ops_center.html"
      - title: Infiniat
        url: "/task_dc_infinidat_infinibox.html"
      - title: Huawei
        url: "/task_dc_huawei_oceanstor.html"
      - title: IBM
        entries:
        - title: Cleversafe
          url: "/task_dc_ibm_cleversafe.html"
        - title: CS Serie
          url: "/task_dc_ibm_cs.html"
        - title: System Storage DS8000 Serie
          url: "/task_dc_ibm_ds.html"
        - title: PowerVM
          url: "/task_dc_ibm_powervm.html"
        - title: San Volume Controller (SVC)
          url: "/task_dc_ibm_svc.html"
        - title: XIV/A9000
          url: "/task_dc_ibm_xiv.html"
      - title: Lenovo
        url: "/task_dc_lenovo.html"
      - title: Microsoft
        entries:
        - title: Azure NetApp Dateien
          url: "/task_dc_ms_anf.html"
        - title: Hyper-V
          url: "/task_dc_ms_hyperv.html"
      - title: NetApp
        entries:
        - title: Astra Data Store
          url: "/task_dc_na_astra_data_store.html"
        - title: Cloud-Anbindung für ONTAP 9.9 oder höher
          url: "/task_dc_na_cloud_connection.html"
        - title: Cloud Volumes ONTAP
          url: "/task_dc_na_cloud_volumes_ontap.html"
        - title: Cloud Volumes Services für AWS
          url: "/task_dc_na_cloud_volumes.html"
        - title: ONTAP Data Management-Software
          url: "/task_dc_na_cdot.html"
        - title: Data ONTAP 7-Mode
          url: "/task_dc_na_7mode.html"
        - title: E-Series
          url: "/task_dc_na_eseries.html"
        - title: NetApp HCI-Verwaltungsserver
          url: "/task_dc_na_hci.html"
        - title: SolidFire
          url: "/task_dc_na_solidfire.html"
        - title: StorageGRID
          url: "/task_dc_na_storagegrid.html"
      - title: Nutanix
        url: "/task_dc_nutanix.html"
      - title: OpenStack
        url: "/task_dc_openstack.html"
      - title: Oracle
        url: "/task_dc_oracle_zfs.html"
      - title: Pure
        url: "/task_dc_pure_flasharray.html"
      - title: Red Hat
        url: "/task_dc_redhat_virtualization.html"
      - title: VMware
        url: "/task_dc_vmware.html"
    - title: Data Collector Reference - Dienste
      entries:
      - title: Host/Node
        url: "/task_config_telegraf_node.html"
      - title: ActiveMQ
        url: "/task_config_telegraf_activemq.html"
      - title: Apache
        url: "/task_config_telegraf_apache.html"
      - title: Konsul
        url: "/task_config_telegraf_consul.html"
      - title: Couchbase
        url: "/task_config_telegraf_couchbase.html"
      - title: CouchDB
        url: "/task_config_telegraf_couchdb.html"
      - title: Docker
        url: "/task_config_telegraf_docker.html"
      - title: Elasticsearch
        url: "/task_config_telegraf_elasticsearch.html"
      - title: Knick
        url: "/task_config_telegraf_flink.html"
      - title: Hadoop
        url: "/task_config_telegraf_hadoop.html"
      - title: HAProxy
        url: "/task_config_telegraf_haproxy.html"
      - title: Java
        url: "/task_config_telegraf_jvm.html"
      - title: Kafka
        url: "/task_config_telegraf_kafka.html"
      - title: Kapacitor
        url: task_config_telegraf_kapacitor.html
      - title: Kibana
        url: "/task_config_telegraf_kibana.html"
      - title: Kubernetes
        url: "/task_config_telegraf_agent.html#kubernetes"
      - title: Gememcachte
        url: "/task_config_telegraf_memcached.html"
      - title: MongoDB
        url: "/task_config_telegraf_mongodb.html"
      - title: MySQL
        url: "/task_config_telegraf_mysql.html"
      - title: Netstat
        url: "/task_config_telegraf_netstat.html"
      - title: Nginx
        url: "/task_config_telegraf_nginx.html"
      - title: OpenZFS
        url: task_config_telegraf_openzfs.html
      - title: PostgreSQL
        url: "/task_config_telegraf_postgresql.html"
      - title: Puppet
        url: "/task_config_telegraf_puppetagent.html"
      - title: Redis
        url: "/task_config_telegraf_redis.html"
      - title: RethinkDB
        url: task_config_telegraf_rethinkdb.html
      - title: Zookeeper
        url: task_config_telegraf_zookeeper.html
    - title: Objekt Symbol Referenz
      url: "/reference_object_icons.html"
  - title: Rechtliche Hinweise
    url: "/reference_legal_notices.html"
