---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr, BlueXP, cloud manager 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch. 
---
= Bekannte Einschränkungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.

Diese Einschränkungen gelten speziell für das Cloud Volumes ONTAP-Management in BlueXP. Um Einschränkungen an der Cloud Volumes ONTAP Software selbst anzuzeigen, https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html["Wechseln Sie zu den Versionshinweisen zu Cloud Volumes ONTAP"^]



== BlueXP unterstützt nicht die Erstellung von FlexGroup Volumes

Cloud Volumes ONTAP unterstützt zwar FlexGroup Volumes, doch BlueXP unterstützt derzeit nicht die Erstellung von FlexGroup Volumes. Wenn Sie ein FlexGroup-Volume aus dem System Manager oder aus der CLI erstellen, sollten Sie den Kapazitätsmanagement-Modus von BlueXP auf manuell einstellen. Der automatische Modus funktioniert möglicherweise nicht ordnungsgemäß mit FlexGroup-Volumes.


NOTE: Die Möglichkeit zum Erstellen von FlexGroup Volumes in BlueXP ist für eine zukünftige Version geplant.



== BlueXP unterstützt S3 nicht mit Cloud Volumes ONTAP

Cloud Volumes ONTAP unterstützt zwar S3 als Option für Scale-out Storage, BlueXP bietet jedoch keine Managementfunktionen für diese Funktion. Als Best Practice empfiehlt sich die Konfiguration des S3-Client-Zugriffs über Cloud Volumes ONTAP mithilfe der CLI. Weitere Informationen finden Sie im http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["S3 Configuration Power Guide"^].

link:concept-client-protocols.html["Weitere Informationen zur Cloud Volumes ONTAP-Unterstützung für S3 und andere Client-Protokolle"].



== BlueXP unterstützt keine Disaster Recovery für Storage VMs

BlueXP bietet keine Unterstützung für die Einrichtung oder Orchestrierung von Disaster Recovery für Storage VMs (SVM). Sie müssen System Manager oder die CLI verwenden.

link:task-manage-svm-dr.html["Erfahren Sie mehr über SVM Disaster Recovery"].



== Testen des AsciiDoc-Zeichenaustauschs und der intrinsischen Attribute

End-to-End-Tests durch Lokalisierung und Veröffentlichung aller Sprachen.

.Sternchen
{Sternchen}
Text{Sternchen}
Text {Sternchen}
Text {Sternchen} Text

.Doppelpunkt
{Zwei Doppelpunkte}
Text{zwei Doppelpunkte}
Text {zwei Doppelpunkte}
Text {zwei Doppelpunkte} Text

.Vertikaler Balken
{vbar}
Text{vbar}
Text {vbar}
Text {vbar} Text

.Plus
{Plus}
Text{plus}
Text {plus}
Text {plus} Text

.Eckige Klammern
{Startsb} und {endsb}
Text{startsb} und Text{endsb}
Text {startsb} und Text {endsb}
Text {startsb} und Text {endsb} Text

.Unzerbrechlich
Vor{nbsp}nach

.Leerraum ohne Breite
Vor{zwsp}nach
