---
sidebar: sidebar 
permalink: reporting_user_roles.html 
summary: Welche Maßnahmen Sie mit Cloud Insights-Reporting tun können, hängt von Ihrer Benutzerrolle ab. 
keywords: reporting, cognos, data warehouse, dwh, users, roles, user roles 
---
= Benutzerrollen Für Cloud Insights-Berichte
:allow-uri-read: 


[role="lead"]
Wenn Sie über Cloud Insights Premium Edition mit Reporting verfügen, verfügt jeder Cloud Insights-Benutzer in Ihrer Umgebung auch über eine SSO-Anmeldung bei der Reporting-Anwendung (d. h. Cognos). Klicken Sie einfach im Menü auf den Link *Berichte* und Sie werden automatisch bei Reporting angemeldet.

Ihre Benutzerrolle in Cloud Insights legt Ihre Rolle für die Berichterstellung fest:

|===


| Cloud Insights Rolle | Berichtsrolle | Reporting-Berechtigungen 


| Gast | Verbraucher | Es können Berichte angezeigt, geplant und erstellt sowie persönliche Einstellungen wie z. B. für Sprachen und Zeitzonen festgelegt werden. Verbraucher können keine Berichte erstellen oder administrative Aufgaben ausführen. 


| Benutzer | Autor | Kann alle Funktionen des Verbrauchers ausführen sowie Berichte und Dashboards erstellen und verwalten. 


| Verwalter | Verwalter | Kann alle Author-Funktionen sowie alle administrativen Aufgaben wie die Konfiguration von Berichten und das Herunterfahren und Neustarten von Reporting-Aufgaben ausführen. 
|===
Die folgende Tabelle zeigt die Funktionen, die den einzelnen Berichtsrollen zur Verfügung stehen.

|===


| Merkmal | Verbraucher | Autor | Verwalter 


| Anzeigen von Berichten auf der Registerkarte „Teaminhalt“ | Ja. | Ja. | Ja. 


| Berichte erstellen | Ja. | Ja. | Ja. 


| Planen von Berichten | Ja. | Ja. | Ja. 


| Externe Dateien hochladen | Nein | Ja. | Ja. 


| Erstellen Von Jobs | Nein | Ja. | Ja. 


| Erstellen von Geschichten | Nein | Ja. | Ja. 


| Erstellen von Berichten | Nein | Ja. | Ja. 


| Erstellen von Paketen und Datenmodulen | Nein | Ja. | Ja. 


| Ausführung administrativer Aufgaben | Nein | Nein | Ja. 
|===


== Festlegen der E-Mail-Einstellungen für Berichte (Cognos)


NOTE: Wenn Sie Ihre Benutzer-E-Mail-Einstellungen innerhalb von Cloud Insights Reporting ändern (d. h. die Cognos-Anwendung), sind diese Einstellungen aktiv_nur für die aktuelle Sitzung_. Wenn Sie sich bei Cognos und wieder zurück in anmelden, werden Ihre E-Mail-Einstellungen zurückgesetzt.



== Wichtiger Hinweis für Bestandskunden

Neue Berichte bei Cloud Insights Es gibt nichts mehr, was Sie tun müssen, um die Berichterstattung zu genießen.

Wenn Sie bereits Premium Edition-Kunde sind, ist SSO für Ihre Umgebung nicht automatisch aktiviert. Wenn Sie SSO aktivieren, existiert der Administrator-Benutzer für das Berichtsportal (Cognos) nicht mehr. Das bedeutet, dass alle Berichte, die sich im Ordner _My Content_ befinden, entfernt werden und in _Team Content_ neu installiert oder neu erstellt werden müssen. Darüber hinaus müssen nach Aktivierung von SSO geplante Berichte konfiguriert werden.



=== Welche Schritte sollte ich Unternehmen, um meine vorhandene Umgebung auf die Aktivierung von SSO vorzubereiten?

Um sicherzustellen, dass Ihre Berichte erhalten bleiben, migrieren Sie alle Berichte von _My Content_ zu _Team Content_. Gehen Sie dabei wie folgt vor. Vor der Aktivierung von SSO in Ihrer Umgebung sind folgende Schritte erforderlich:

. Erstellen Sie einen neuen Ordner in _Team Content_
+
.. Wenn mehrere Benutzer erstellt wurden, erstellen Sie für jeden Benutzer einen separaten Ordner, um zu vermeiden, dass Berichte mit doppelten Namen überschrieben werden


. Navigieren Sie zu _My Content_
. Wählen Sie alle Berichte aus, die Sie beibehalten möchten.
. Wählen Sie oben rechts im Menü die Option „Kopieren oder Verschieben“ aus.
. Navigieren Sie zum neu erstellten Ordner in _Team Content_
. Fügen Sie die Berichte mithilfe der Schaltflächen „Kopieren nach“ oder „Verschieben nach“ in den neu erstellten Ordner ein
. Sobald SSO für Cognos aktiviert ist, melden Sie sich bei Cloud Insights an, wobei die E-Mail-Adresse zum Erstellen Ihres Kontos verwendet wird.
. Navigieren Sie in Cognos zum Ordner „_Team Content_“, und kopieren oder verschieben Sie die zuvor gespeicherten Berichte zurück zu „_My Content_“.

