---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: Vordefinierte und individuelle Berichterstellung Ihrer Daten mit Cloud Insights 
keywords: reporting, cognos, data warehouse, dwh 
---
= Cloud Insights-Berichte: Überblick
:allow-uri-read: 


[role="lead"]
Cloud Insights Berichte sind ein Business Intelligence Tool, mit dem Sie vordefinierte Berichte anzeigen oder individuelle Berichte erstellen können.


NOTE: Die Berichtsfunktion ist in Cloud Insights verfügbar link:concept_subscribing_to_cloud_insights.html["Premium Edition"].

Mit Cloud Insights Reporting können Sie die folgenden Aufgaben durchführen:

* Führen Sie einen vordefinierten Bericht aus
* Erstellen Sie einen benutzerdefinierten Bericht
* Passen Sie das Format und die Bereitstellungsmethode eines Berichts an
* Planen Sie die automatische Ausführung von Berichten
* E-Mail-Berichte
* Verwenden Sie Farben, um Schwellenwerte für Daten darzustellen


Cloud Insights-Berichte können benutzerdefinierte Berichte für Bereiche wie Chargeback, Verbrauchsanalysen und Prognosen erstellen. Darüber hinaus bieten sie Unterstützung bei der Beantwortung von Fragen wie folgenden:

* Welche Bestände habe ich?
* Wo ist mein Inventar?
* Wer nutzt unsere Ressourcen?
* Wie sieht die Rückberechnung von zugewiesenem Storage für einen Geschäftsbereich aus?
* Wie lange dauert es, bis ich zusätzliche Storage-Kapazität anschaffen muss?
* Werden die Geschäftseinheiten auf die entsprechenden Storage Tiers abgestimmt?
* Inwiefern ändert sich die Storage-Zuweisung über einen Monat, ein Quartal oder ein Jahr?




== Zugriff Auf Cloud Insights-Berichte

Sie können auf Cloud Insights-Berichte zugreifen, indem Sie im Menü auf den Link *Berichte* klicken.

Sie werden zur Berichtsschnittstelle geleitet. Cloud Insights verwendet für seine Reporting Engine IBM Cognos Analytics. Melden Sie sich mit Ihren Anmeldedaten für Berichte an.



== Was ist ETL?

Bei der Arbeit mit Reporting hören Sie die Begriffe „Data Warehouse“ und „ETL“. ETL steht für „Extract, Transform, Load“. Der ETL-Prozess ruft in Cloud Insights gesammelte Daten ab und wandelt diese in ein Format um, das für die Berichterstellung verwendet werden kann. „Data Warehouse“ bezieht sich auf die gesammelten Daten, die für die Berichterstattung zur Verfügung stehen.

Der ETL-Prozess umfasst folgende Einzelprozesse:

* *Extrakt*: Nimmt Daten aus Cloud Insights.
* *Transform*: Wendet Geschäftslogik Regeln oder Funktionen auf die Daten an, wie sie aus Cloud Insights extrahiert werden.
* *Load*: Speichert die umgewandelten Daten in das Data Warehouse zur Verwendung in Reporting.

