---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Konfiguration von Red hat Virtualization Data Collector 
---
= Datensammler Red hat Virtualization
:allow-uri-read: 


[role="lead"]
Cloud Insights verwendet den Red hat Virtualization Data Collector, um Bestandsdaten von virtualisierten Linux- und Microsoft Windows-Workloads zu erfassen.



== Terminologie

Für jeden von Cloud Insights erfassten Asset-Typ wird die am häufigsten für die Ressource verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Festplatte | Virtuelles Laufwerk 


| Host | Host 


| Virtual Machine | Virtual Machine 


| Storage Domain | Datastore 


| Logische Einheit | LUN 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* IP-Adresse des RHEV-Servers über Port 443 über REST-API
* Nur-Lese-Benutzername und Kennwort
* RHEV Version 3.0+




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| RHEV-Server-IP-Adresse | IP-Adresse des Storage-Systems 


| Benutzername | Benutzername mit Administratorrechten 


| Passwort für das Administratorkonto | Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HTTPS-Kommunikationsschnittstelle | Port, der für die HTTPS-Kommunikation mit RHEV verwendet wird 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 20 Minuten. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
