---
sidebar: sidebar 
permalink: task_cs_add_collector_ontap.html 
keywords: data collector, ONTAP, SVM 
summary: Hinzufügen von Datensammlern 
---
= Konfigurieren des NetApp ONTAP Data Collectors
:allow-uri-read: 


[role="lead"]
Cloud Secure verwendet Datensammler, um Datei- und Benutzerzugriffsdaten von Geräten zu erfassen. Die Daten werden Cloud Secure zur Analyse zur Verfügung gestellt.

.Bevor Sie beginnen
Sie benötigen die folgenden Informationen, um diesen Datensammler zu konfigurieren:

* Ein Agent muss für das Sammeln von Daten konfiguriert sein
* Die SVM-Management-IP-Adresse
* Ein Benutzername für den Zugriff auf die SVM
* Das Passwort für den Zugriff auf die SVM


.Schritte zur Konfiguration
. Melden Sie sich als Administrator oder Account-Inhaber in Ihrer Cloud Secure-Umgebung an.
. Klicken Sie Auf *Admin > Datensammler > +Datensammler*
+
Das System zeigt die verfügbaren Datensammler an.

. Klicken Sie auf *+Monitor* in der Kachel NetApp ONTAP.
+
Das System zeigt die Konfigurationsseite Data Collector: ONTAP SVM hinzufügen an.

. Geben Sie einen eindeutigen Namen für den Sammler ein
. Wählen Sie den Agenten aus, der die Daten sammelt
. Geben Sie die SVM-Management-IP-Adresse ein
. Geben Sie den Benutzernamen für den Zugriff auf die SVM ein
. Geben Sie das Passwort für den Zugriff auf die SVM ein
. Klicken Sie Auf *+Collector Hinzufügen*


.Nachdem Sie fertig sind
* Klicken Sie auf *Admin > Data Collectors*, um den Status des von Ihnen konfigurierten Collectors zu überprüfen.
+
Es liegt normalerweise eine Verzögerung vor der Anzeige des Kollektorstatus vor.


