---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: NetApp StorageGRID Data Collector konfigurieren 
keywords: data collector, queries, create, storagegrid 
---
= NetApp StorageGRID Datensammler
:allow-uri-read: 


[role="lead"]
Der NetApp StorageGRID Datensammler unterstützt Inventar- und Performance-Sammlung aus StorageGRID Konfigurationen.


NOTE: StorageGRID wird mit einem eigenen Raw TB für die gemanagte Einheit gemessen. Jede unformatierte StorageGRID-Kapazität von 40 TB wird als 1 berechnet link:concept_subscribing_to_cloud_insights.html#pricing["Verwaltete Einheit (ME)"].



== Anforderungen

Für die Konfiguration dieser Datenquelle gelten folgende Anforderungen:

* StorageGRID-Host-IP-Adresse
* Ein Benutzername und ein Passwort für einen Benutzer, dem die Rollen Metric Query und Tenant Access zugewiesen sind
* Port 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| StorageGRID-Host-IP-Adresse | Management der virtuellen IP-Adresse der StorageGRID Appliance 


| Benutzername | Name, der zur Anmeldung bei der StorageGRID Appliance verwendet wird 


| Passwort | Passwort, das zur Anmeldung bei der StorageGRID Appliance verwendet wird 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 60 Minuten 


| Leistungsintervall (Sek.) | Der Standardwert ist 900 Sekunden 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
