---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: IBM TotalStorage DS4000 Datensammler 
---
= IBM TotalStorage DS4000 Datensammler
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Performance-Informationen aus dem IBM DS4000 Storage-System. Es gibt zwei mögliche Konfigurationen (Firmware 6.x und Firmware 7.x+), und beide haben die gleichen Werte.



== Terminologie

Cloud Insightst erwirbt die folgenden Bestandsinformationen vom IBM DS4000 Datensammler. Für jeden erfassten Asset-Typ wird die am häufigsten für dieses Dokument verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Festplatte | Festplatte 


| Volume-Gruppe | Festplattengruppe 


| Storage Array Durchführt | Storage 


| Controller | Storage-Node 


| Volume-Gruppe | Storage-Pool 


| Datenmenge | Datenmenge 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Die IP-Adresse jedes DS5- oder FAStT-Arrays
* Zugriffsvalidierung durch Ping der IP-Adresse beider Controller auf dem Array
* Port-Anforderungen: 2463




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Kommagetrennte Liste der Array-SANtricity-Controller-IPs | IP-Adressen und/oder vollqualifizierte Domain-Namen für die Array Controller 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 30 Minuten 


| Leistungsintervall bis zu 3600 Sekunden | Der Standardwert ist 300 Sekunden 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
