---
sidebar: sidebar 
permalink: task-setting-up-gcp-encryption.html 
keywords: encryption, gcp, encryption key, permissions, customer-managed, gcpencryption 
summary: Während Google Cloud Storage immer verschlüsselt Ihre Daten, bevor es auf Festplatte geschrieben wird, können Sie BlueXP APIs verwenden, um ein Cloud Volumes ONTAP-System zu erstellen, das vom Kunden verwaltete Verschlüsselungsschlüssel verwendet. Diese Schlüssel werden in GCP mithilfe des Cloud Key Management Service generiert und gemanagt. 
---
= Nutzung von vom Kunden gemanagten Schlüsseln mit Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Während Google Cloud Storage Ihre Daten immer verschlüsselt, bevor sie auf die Festplatte geschrieben werden, können Sie mithilfe der BlueXP API ein Cloud Volumes ONTAP-System erstellen, das _vom Kunden verwaltete Verschlüsselungsschlüssel_ verwendet. Diese Schlüssel werden in GCP mithilfe des Cloud Key Management Service generiert und gemanagt.

.Schritte
. Stellen Sie sicher, dass das Servicekonto BlueXP Connector im Projekt, in dem der Schlüssel gespeichert ist, über die entsprechenden Berechtigungen auf Projektebene verfügt.
+
Die Berechtigungen werden im bereitgestellt https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["Standardmäßig sind die Berechtigungen für das Connector-Dienstkonto festgelegt"^], Kann aber nicht angewendet werden, wenn Sie ein alternatives Projekt für den Cloud Key Management Service verwenden.

+
Folgende Berechtigungen stehen zur Auswahl:

+
[source, yaml]
----
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
----
. Stellen Sie sicher, dass das Servicekonto für das https://cloud.google.com/iam/docs/service-agents["Google Compute Engine Service Agent"^] Hat Cloud KMS-Verschlüsselung/Dekrypter-Berechtigungen auf dem Schlüssel.
+
Der Name des Dienstkontos verwendet das folgende Format: "Service-[Service_project_number]@compute-system.iam.gserviceaccount.com".

+
https://cloud.google.com/kms/docs/iam#granting_roles_on_a_resource["Google Cloud Documentation: IAM mit Cloud KMS nutzen - Rollenverteilung auf einer Ressource"]

. Rufen Sie die „id“ des Schlüssels ab, indem Sie den Befehl get für das aufrufen `/gcp/vsa/metadata/gcp-encryption-keys` API-Anruf oder durch Auswahl des „Copy Resource Name“ auf dem Schlüssel in der GCP-Konsole.
. Wenn Sie vom Kunden verwaltete Schlüssel und Tiering-Daten in Objekt-Storage verwenden, versucht BlueXP, dieselben Schlüssel zu verwenden, die zur Verschlüsselung der persistenten Festplatten verwendet werden. Zunächst müssen Sie Google Cloud Storage Buckets aktivieren, um die Schlüssel zu verwenden:
+
.. Suchen Sie den Google Cloud Storage Service Agent, indem Sie den folgenden folgen https://cloud.google.com/storage/docs/getting-service-agent["Google Cloud Documentation: Die Bereitstellung des Cloud Storage-Service-Agenten"^].
.. Navigieren Sie zum Verschlüsselungsschlüssel und weisen Sie den Google Cloud Storage Service Agent mit Cloud KMS Verschlüsselungs-/Dekrypter-Berechtigungen zu.


+
Weitere Informationen finden Sie unter https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys["Google Cloud Documentation: Nutzung von vom Kunden gemanagten Verschlüsselungsschlüsseln"^]

. Verwenden Sie bei der Erstellung einer Arbeitsumgebung den Parameter „GcpEncryption“ in Verbindung mit Ihrer API-Anforderung.
+
*Beispiel*

+
[source, json]
----
"gcpEncryptionParameters": {
    "key": "projects/project-1/locations/us-east4/keyRings/keyring-1/cryptoKeys/generatedkey1"
  }
----


Siehe https://docs.netapp.com/us-en/bluexp-automation/index.html["BlueXP Automation Dokumentation"^] Weitere Informationen zur Verwendung des Parameters „GcpEncryption“.
