---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: Sie erstellen Anmerkungsregeln, um Anmerkungen automatisch auf mehrere Assets anzuwenden. 
---
= Anmerkungsregeln werden erstellt
:allow-uri-read: 


[role="lead"]
Mit Anmerkungsregeln können Sie Anmerkungen automatisch auf mehrere Assets anwenden, die auf den von Ihnen definierten Kriterien basieren. Cloud Insights weist anhand dieser Regeln Anmerkungen zu Assets zu. Wenn Cloud Insight die Anmerkungsregeln auswertet, haben Annotationen, die manuell auf den Seiten einzelner Assets festgelegt wurden, Vorrang vor regelbasierten Annotationen.

.Bevor Sie beginnen
Sie müssen eine Abfrage für die Anmerkungsregel erstellt haben.

.Schritte
. Klicken Sie im Menü Cloud Insights auf *Verwalten > Anmerkungsregeln*.
. Klicken Sie auf *+ Regel*, um eine neue Anmerkungsregel hinzuzufügen.
+
Das Dialogfeld Regel hinzufügen wird angezeigt.

. Gehen Sie wie folgt vor:
+
.. Geben Sie im Feld *Name* einen eindeutigen Namen ein, der die Regel beschreibt.
+
Der Name wird auf der Seite Anmerkungsregeln angezeigt.

.. Klicken Sie auf *Query* und wählen Sie die Abfrage aus, die Cloud Insights verwendet, um die Assets zu identifizieren, für die die Anmerkung gilt.
.. Klicken Sie auf *Anmerkung* und wählen Sie die Beschriftung aus, die Sie anwenden möchten.
.. Klicken Sie auf *Wert* und wählen Sie einen Wert für die Anmerkung aus.
+
Wenn Sie beispielsweise als Anmerkung Geburtstag auswählen, geben Sie ein Datum für den Wert an.

.. Klicken Sie Auf *Speichern*
.. Klicken Sie auf *Alle Regeln*, wenn Sie alle Regeln sofort ausführen möchten; andernfalls werden die Regeln in einem regelmäßigen geplanten Intervall ausgeführt.
+

NOTE: In einer großen Cloud Insights-Umgebung fällt möglicherweise auf, dass das Ausführen von Anmerkungsregeln etwas Zeit in Anspruch nehmen scheint. Dies liegt daran, dass der Indexer zuerst ausgeführt wird und vor der Ausführung der Regeln abgeschlossen werden muss. Mit dem Indexer kann Cloud Insights nach neuen oder aktualisierten Objekten und Zählern in Ihren Daten suchen oder filtern. Die Regel-Engine wartet, bis der Indexer seine Aktualisierung abgeschlossen hat, bevor die Regeln angewendet werden.







== Anmerkungsregeln ändern

Sie können eine Anmerkungsregel ändern, um den Namen der Regel, ihre Anmerkung, den Wert der Anmerkung oder die mit der Regel verknüpfte Abfrage zu ändern.

.Schritte
. Klicken Sie im Menü Cloud Insights auf *Verwalten > Anmerkungsregeln*.
+
Auf der Seite Anmerkungsregeln wird die Liste der vorhandenen Anmerkungsregeln angezeigt.

. Suchen Sie die Anmerkungsregel, die Sie ändern möchten.
+
Sie können die Anmerkungsregeln filtern, indem Sie einen Wert in das Filterfeld eingeben oder auf eine Seitenzahl klicken, um die Anmerkungsregeln nach Seite zu durchsuchen.

. Klicken Sie auf das Menüsymbol für die Regel, die Sie ändern möchten.
. Klicken Sie Auf *Bearbeiten*
+
Das Dialogfeld Regel bearbeiten wird angezeigt.

. Ändern Sie den Namen, die Anmerkungen, den Wert oder die Abfrage der Anmerkungsregel.




== Die Reihenfolge der Regeln ändern

Anmerkungsregeln werden von oben in der Regelliste bis unten verarbeitet. Um die Reihenfolge zu ändern, in der eine Regel verarbeitet wird, gehen Sie wie folgt vor:

.Schritte
. Klicken Sie auf das Menüsymbol für die Regel, die Sie verschieben möchten.
. Klicken Sie nach Bedarf auf *nach oben* oder *nach unten bewegen*, bis die Regel an dem gewünschten Ort angezeigt wird.




== Anmerkungsregeln werden gelöscht

Möglicherweise möchten Sie Anmerkungsregeln löschen, die nicht mehr verwendet werden.

.Schritte
. Klicken Sie im Menü Cloud Insights auf *Verwalten > Anmerkungsregeln*.
+
Auf der Seite Anmerkungsregeln wird die Liste der vorhandenen Anmerkungsregeln angezeigt.

. Suchen Sie die Anmerkungsregel, die gelöscht werden soll.
+
Sie können die Anmerkungsregeln filtern, indem Sie einen Wert in das Filterfeld eingeben oder auf eine Seitenzahl klicken, um die Anmerkungsregeln nach Seite zu durchsuchen.

. Klicken Sie auf das Menüsymbol für die Regel, die Sie löschen möchten.
. Klicken Sie Auf *Löschen*
+
Es wird eine Bestätigungsmeldung angezeigt, in der Sie gefragt werden, ob Sie die Regel löschen möchten.

. Klicken Sie auf *OK*

