---
sidebar: sidebar 
permalink: task_dc_hds_commandsuite.html 
keywords: data collector, Hitachi Vantara Command Suite, Hitachi 
summary: Konfiguration des HDS Command Suite Device Manager-Datensammlers 
---
= Datensammler der Hitachi Vantara Command Suite
:allow-uri-read: 


[role="lead"]
Der Datensammler der Hitachi Vantara Command Suite unterstützt den HiCommand Device Manager-Server. Cloud Insights kommuniziert mit dem HiCommand Device Manager-Server über die standardmäßige HiCommand API.



== Terminologie

Cloud Insights erfasst die folgenden Bestandsinformationen vom Datensammler der Hitachi Vantara Command Suite. Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| PDEV | Festplatte 


| Journalpool | Festplattengruppe 


| Storage Array Durchführt | Storage 


| Port Controller | Storage-Node 


| Array-Gruppe, HDS Pool | Storage-Pool 


| Logische Einheit, LDEV | Datenmenge 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



=== Storage

Die folgenden Begriffe beziehen sich auf Objekte oder Referenzen, die auf HDS Storage Asset Landing Pages zu finden sind. Viele dieser Bedingungen gelten auch für andere Datensammler.

* Name – kommt direkt aus dem Attribut „Name“ des HDS HiCommand Device Managers über den GetStorageArray XML API-Aufruf
* Modell - kommt direkt aus dem „arrayType“-Attribut des HDS HiCommand Device Managers über den GetStorageArray XML API-Aufruf
* Anbieter – HDS
* Family - kommt direkt aus dem Attribut „arrayFamily“ des HDS HiCommand Device Managers über den GetStorageArray XML API-Aufruf
* IP – hierbei handelt es sich um die Management-IP-Adresse des Arrays, keine vollständige Liste aller IP-Adressen im Array
* Rohkapazität: Ein base2-Wert, der die Summe der Gesamtkapazität aller Festplatten in diesem System darstellt, unabhängig von der Festplattenrolle.




=== Storage-Pool

Die folgenden Begriffe beziehen sich auf Objekte oder Referenzen, die auf HDS Storage Pool Asset Landing Pages zu finden sind. Viele dieser Bedingungen gelten auch für andere Datensammler.

* Typ: Der Wert hier ist einer von:
+
** RESERVIERT – Wenn dieser Pool für andere Zwecke als Datenvolumes, i.e, Journaling, Snapshots bestimmt ist
** Thin Provisioning – wenn es sich um einen HDP-Pool handelt
** RAID-Gruppe – aus ein paar Gründen werden Sie diese wahrscheinlich nicht sehen:
+
Cloud Insights ist ein starker Standpunkt, um eine doppelte Zählung von Kapazität bei allen Kosten zu vermeiden. Auf HDS muss man normalerweise RAID-Gruppen von Festplatten erstellen, Pool-Volumes auf diesen RAID-Gruppen erstellen und Pools (oft HDP, könnte aber besonderer Zweck sein) aus diesen Pool Volumes erstellen. Wenn Cloud Insights sowohl die zugrunde liegenden RAID Gruppen als auch die Pools gemeldet hat, würde die Summe ihrer Bruttokapazität die Summe der Festplatten deutlich übersteigen.

+
Stattdessen reduziert der Datensammler der Cloud Insights HDS Command Suite die Größe von RAID-Gruppen willkürlich um die Kapazität von Pool Volumes. Dies kann dazu führen, dass Cloud Insights die RAID-Gruppe überhaupt nicht meldet. Darüber hinaus werden alle resultierenden RAID-Gruppen so gekennzeichnet, dass sie in der Cloud Insights WebUI nicht sichtbar sind, doch fließen sie in das Cloud Insights Data Warehouse (DWH). Der Zweck dieser Entscheidungen ist es, UI-Gerinnung für Dinge zu vermeiden, die den meisten Benutzern egal sind – wenn Ihr HDS-Array RAID-Gruppen mit 50 MB frei hat, können Sie diesen freien Speicherplatz wahrscheinlich nicht für ein sinnvolles Ergebnis nutzen.



* Node – k. A., da HDS Pools nicht an einen bestimmten Node gebunden sind
* Redundanz: Der RAID-Level des Pools. Möglicherweise mehrere Werte für einen HDP-Pool, die aus mehreren RAID-Typen bestehen
* Kapazität % - der Prozentsatz, der für die Datenverwendung des Pools verwendet wird, wobei die verwendete GB und die gesamte logische GB-Größe des Pools verwendet werden
* Überzuviel Kapazität - ein abgeleiteter Wert, der angibt, „die logische Kapazität dieses Pools wird durch diesen Prozentsatz überzeichnet, aufgrund der Summe der logischen Volumes, die die logische Kapazität des Pools um diesen Prozentsatz überschreiten“
* Snapshot - zeigt die Kapazität an, die für die Snapshot-Nutzung in diesem Pool reserviert ist




=== Storage-Node

Die folgenden Begriffe beziehen sich auf Objekte oder Referenzen, die auf den HDS Storage Node Asset Landing Pages zu finden sind. Viele dieser Bedingungen gelten auch für andere Datensammler.

* Name: Der Name des Front-End-Director (FED) oder Channel-Adapters auf monolithischen Arrays oder der Name des Controllers auf einem modularen Array. Ein bestimmtes HDS-Array verfügt über zwei oder mehr Storage-Nodes
* Volumes – die Volume-Tabelle zeigt jedes Volume an, das einem beliebigen Port dieses Speicherknoten zugeordnet ist




== Inventaranforderungen

Zur Erfassung von Bestandsdaten müssen Sie Folgendes haben:

* IP-Adresse des HiCommand Device Manager-Servers
* Schreibgeschützter Benutzername und Kennwort für die HiCommand Device Manager-Software und Peer-Berechtigungen
* Port-Anforderungen: 2001 (http) oder 2443 (https)
* Melden Sie sich mit Benutzernamen und Kennwort bei der HiCommand Device Manager-Software an
* Überprüfen Sie den Zugriff auf HiCommand Device Manager http://<HiCommand_Device_Manager_IP>:2001/service/StorageManager[]




== Performance-Anforderungen erfüllt

Zur Erfassung von Leistungsdaten müssen die folgenden Anforderungen erfüllt sein:

* HDS USP, USP V und VSP Performance
+
** Performance Monitor muss lizenziert sein.
** Überwachungsschalter muss aktiviert sein.
** Das Exportwerkzeug (Export.exe) muss in die Cloud Insights AU kopiert werden.
** Die Version des Exportwerkzeugs muss mit der Microcode-Version des Ziel-Arrays übereinstimmen.


* AMS-Leistung:
+
** NetApp empfiehlt: Erstellen eines dedizierten Servicekontos auf AMS Arrays für Cloud Insights zum Abrufen von Performance-Daten. Storage Navigator ermöglicht nur ein Benutzerkonto, das gleichzeitig mit dem Array angemeldet ist. Wenn Cloud Insights dasselbe Benutzerkonto wie Verwaltungsskripte oder HiCommand verwendet, kann dies dazu führen, dass Cloud Insights, Verwaltungsskripte oder HiCommand aufgrund der Eins-Grenze für gleichzeitige Benutzerkontoanmeldedaten nicht mit dem Array kommunizieren kann
** Performance Monitor muss lizenziert sein.
** Das CLI-Dienstprogramm Storage Navigator Modular 2 (SNM2) muss auf der Cloud Insights AU installiert sein.






== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| HiCommand Server | IP-Adresse oder vollqualifizierter Domänenname des HiCommand Device Manager-Servers 


| Benutzername | Benutzername für den HiCommand Device Manager-Server. 


| Passwort | Passwort, das für den HiCommand Device Manager-Server verwendet wird. 


| GERÄTE – VSP G1000 (R800), VSP (R700), HUS VM (HM700) UND USP-SPEICHER | Geräteliste für VSP G1000 (R800), VSP (R700), HUS VM (HM700) und USP-Speicher. Jeder Speicher benötigt: * Array IP: IP-Adresse des Speichers * Benutzername: Benutzername für den Speicher * Passwort: Passwort für den Speicher * Ordner mit Export Utility JAR-Dateien 


| SNM2Geräte - WMS/SMS/AMS-Speicher | Geräteliste für WMS/SMS/AMS-Speicher. Jeder Speicher benötigt: * Array's IP: IP address of the Storage * Storage Navigator CLI Pfad: SNM2 CLI Pfad * Konto Authentifizierung gültig: Wählen Sie gültige Konto Authentifizierung * Benutzername: Benutzername für den Speicher * Passwort: Passwort für den Speicher 


| Wählen Sie Tuning Manager für Leistung | Andere Leistungsoptionen überschreiben 


| Tuning Manager Host | IP-Adresse oder vollqualifizierter Domain-Name des Tuning Managers 


| Tuning Manager-Port Überschreiben | Wenn leer, verwenden Sie den Standardport im Feld Tuning Manager für Performance auswählen. Geben Sie andernfalls den zu verwendenden Port ein 


| Benutzername Für Tuning Manager | Benutzername für Tuning Manager 


| Kennwort Für Tuning-Manager | Passwort für Tuning Manager 
|===
Hinweis: Bei HDS USP, USP V und VSP kann jede Festplatte zu mehr als einer Array-Gruppe gehören.



== Erweiterte Konfiguration

|===


| Feld | Beschreibung 


| Verbindungstyp | HTTPS oder HTTP: Zeigt auch den Standardport an 


| HiCommand Server-Port | Port, der für den HiCommand Device Manager verwendet wird 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 40. 


| Wählen Sie „Ausschließen“ oder „Einschließen“, um eine Liste anzugeben | Geben Sie an, ob die unten aufgeführte Array-Liste beim Sammeln von Daten aufgenommen oder ausgeschlossen werden soll. 


| Geräteliste filtern | Kommagetrennte Liste der einzuschließenden oder auszuschließenden Geräteseriennummer 


| Leistungsintervall (Sek.) | Intervall zwischen Performance-Abstimmungen Der Standardwert ist 300. 


| Ausfuhrzeitlimit in Sekunden | Zeitüberschreitung beim Exportieren der Dienstprogrammfunktion. Der Standardwert ist 300. 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



==== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: Benutzer hat nicht genügend Berechtigung | Verwenden Sie ein anderes Benutzerkonto, das über mehr Berechtigungen verfügt oder die Berechtigung des Benutzerkontos, das im Datensammler konfiguriert ist, erhöht 


| Fehler: Speicherliste ist leer. Entweder sind Geräte nicht konfiguriert oder der Benutzer verfügt nicht über ausreichende Berechtigungen | * Verwenden Sie DeviceManager, um zu überprüfen, ob die Geräte konfiguriert sind. * Verwenden Sie ein anderes Benutzerkonto, das mehr Berechtigungen hat, oder erhöhen Sie die Berechtigung des Benutzerkontos 


| Fehler: HDS Speicher-Array wurde einige Tage lang nicht aktualisiert | Untersuchen Sie, warum dieses Array nicht in HDS HiCommand aktualisiert wird. 
|===


==== Leistung

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: * Fehler beim Ausführen des Exportdienstprogramms * Fehler beim Ausführen des externen Befehls | * Bestätigen Sie, dass Exportdienstprogramm auf der Cloud Insights-Erfassungseinheit installiert ist * Bestätigen Sie, dass der Speicherort des Exportdienstprogramms in der Konfiguration des Datensammlers korrekt ist * Bestätigen Sie, dass die IP des USP/R600-Arrays in der Konfiguration des Datensammlers korrekt ist. * Bestätigen Sie den Benutzernamen Und das Passwort ist in der Konfiguration des Datensammlers korrekt. * Bestätigen Sie, dass die Version des Exportdienstprogramms mit der Microcode-Version des Speicherarrays * von der Cloud Insights-Erfassungseinheit kompatibel ist, öffnen Sie eine CMD-Eingabeaufforderung und gehen Sie wie folgt vor: - Ändern Sie das Verzeichnis in das konfigurierte Installationsverzeichnis - Versuchen Sie, eine Verbindung mit dem konfigurierten Speicher-Array herzustellen, indem Sie die Batch-Datei runWin.bat ausführen 


| Fehler: Export Tool-Anmeldung für Ziel-IP fehlgeschlagen | * Bestätigen Sie, dass Benutzername/Passwort korrekt ist * Erstellen Sie eine Benutzer-ID hauptsächlich für diesen HDS-Datensammler * Bestätigen Sie, dass keine anderen Datensammler für die Erfassung dieses Arrays konfiguriert sind 


| Fehler: Exportwerkzeuge protokolliert "Zeitbereich für Überwachung nicht abrufen". | * Bestätigung der Leistungsüberwachung auf dem Array ist aktiviert. * Versuchen Sie, die Exportwerkzeuge außerhalb von Cloud Insights zu aktivieren, um zu bestätigen, dass das Problem außerhalb von Cloud Insights liegt. 


| Fehler: * Konfigurationsfehler: Speicher-Array wird vom Exportdienstprogramm nicht unterstützt * Konfigurationsfehler: Speicher-Array wird nicht von Speicher-Navigator Modular CLI unterstützt | * Nur unterstützte Storage-Arrays konfigurieren. * Verwenden Sie „Filter Device List“, um nicht unterstützte Speicher-Arrays auszuschließen. 


| Fehler: * Fehler beim Ausführen des externen Befehls * Konfigurationsfehler: Speicher-Array nicht gemeldet von Inventory * Konfigurationsfehler:Exportordner enthält keine JAR-Dateien | * Überprüfen Sie den Speicherort des Exportdienstprogramms. * Prüfen Sie, ob Speicher-Array in Frage in HiCommand Server konfiguriert ist * Festlegen des Performance-Abfrageintervalls als mehrere 60 Sekunden. 


| Fehler: * Fehler Storage Navigator CLI * Fehler beim Ausführen von auPerform Befehl * Fehler beim Ausführen des externen Befehls | * Bestätigen Sie, dass Speicher-Navigator Modular CLI auf der Cloud Insights-Erfassungseinheit installiert ist * Bestätigen Sie, dass der modulare Speicher-CLI-Standort in der Datenerfassungs-Konfiguration korrekt ist * Bestätigen Sie, dass die IP des WMS/SMS/SMS-Arrays in der Konfiguration des Datensammlers korrekt ist * Bestätigen Dass Speicher-Navigator Modular CLI-Version mit einer Mikrocode-Version des Speicherarrays kompatibel ist, die im Datensammler * von der Cloud Insights-Erfassungseinheit konfiguriert ist, öffnen Sie eine CMD-Eingabeaufforderung und gehen Sie wie folgt vor: - Ändern Sie das Verzeichnis in das konfigurierte Installationsverzeichnis - Versuchen Sie, eine Verbindung mit dem konfigurierten Speicher-Array herzustellen, indem Sie den folgenden Befehl „auunitref.exe“ ausführen. 


| Fehler: Konfigurationsfehler: Speicher-Array wird vom Inventory nicht gemeldet | Überprüfen Sie, ob Speicher-Array in Frage im HiCommand-Server konfiguriert ist 


| Fehler: * Kein Array ist beim Speicher Navigator Modular 2 CLI registriert * Array ist nicht bei der Speicher Navigator Modular 2 CLI registriert * Konfigurationsfehler: Speicher-Array nicht bei StorageNavigator Modular CLI registriert | * Eingabeaufforderung öffnen und Verzeichnis auf den konfigurierten Pfad ändern * Ausführen des Befehls „set=STONAVM_HOME=.“ * Ausführen des Befehls „auunitref“ * Bestätigen Sie, dass die Befehlsausgabe Details des Arrays mit IP * enthält. Wenn die Ausgabe nicht die Array-Details enthält, registrieren Sie das Array mit Storage Navigator CLI: - Eingabeaufforderung öffnen und Verzeichnis auf den konfigurierten Pfad ändern - Befehl „set=STONAVM_HOME= ausführen.“ - Ausführen des Befehls „auunitaddAuto -ip €{ip}“. Ersetzen Sie{ip} durch echtes IP 
|===
Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
