---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: VNX-Datensammler konfigurieren. 
---
= Konfigurieren des Dell EMC VNX Unified Data Collectors
:allow-uri-read: 


[role="lead"]
Für die Konfiguration benötigt der Dell EMC VNX Unified (SSH)-Datensammler die IP-Adresse der Control Station sowie einen schreibgeschützten Benutzernamen und ein Kennwort.



== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen von diesem Datensammler. Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Festplatte | Festplatte 


| Festplattenordner | Festplattengruppe 


| File-System | Internes Volumen 


| Storage | Storage 


| Storage Processor | Storage-Node 


| Speicherpool, RAID-Gruppe | Storage-Pool 


| LUN | Datenmenge 


| Data Mover | Controller 


| Auf einem Data Mover gemountet | Dateifreigabe 


| CIFS- und NFS-Exporte | Share 


| Festplatten-Volume | Back-End LUN 
|===


== Anforderungen

Sie benötigen Folgendes, um den VNX (SSH) Data Collector zu konfigurieren:

* VNX-IP-Adresse und Anmeldeinformationen an der Celerra Control Station.
* Nur-Lese-Benutzername und Kennwort.
* Der Datensammler kann NaviCLI/NaviSecCLI Befehle gegen das Backend-Array ausführen, das die DART OS NAS Heads verwendet




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| VNX-IP-Adresse | IP-Adresse oder vollqualifizierter Domänenname der VNX Control Station 


| Benutzername | Benutzername für die VNX Control Station 


| Passwort | Kennwort für die VNX Control Station 
|===


== Erweiterte Konfigiration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 40 Minuten. 


| Leistungsintervall (Sek.). | Intervall zwischen Performance-Abstimmungen Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
