---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: Mithilfe der Geräteauflösung können Sie die Leistung und den Bestand in Ihrer Umgebung genau verfolgen. 
---
= Regeln zur Geräterauflösung
:allow-uri-read: 


[role="lead"]
Sie erstellen Geräterauflösungsregeln, um Hosts, Storage und Tapes zu identifizieren, die derzeit nicht automatisch von Cloud Insights ermittelt werden. Die Regeln, die Sie erstellen, identifizieren Geräte, die sich derzeit in Ihrer Umgebung befinden, und identifizieren ähnliche Geräte, die Ihrer Umgebung hinzugefügt werden.



== Geräterauflösungsregeln Werden Erstellt

Wenn Sie Regeln erstellen, müssen Sie zunächst die Informationsquelle identifizieren, auf die die Regel angewendet wird, die Methode, mit der Informationen extrahiert werden sollen, und ob DNS-Suche auf die Ergebnisse der Regel angewendet wird.

[cols="2*"]
|===


| Quelle, mit der das Gerät identifiziert wird | * SRM Aliase für Hosts * Storage-Alias mit eingebettetem Host- oder Bandnamen * Switch-Alias, der einen eingebetteten Host- oder Bandnamen enthält * Zonennamen, die einen eingebetteten Hostnamen enthalten 


| Methode, die zum Extrahieren des Gerätenamens aus der Quelle verwendet wird | * AS (einen Namen aus einem SRM extrahieren) * Trennzeichen * reguläre Ausdrücke 


| DNS-Suche | Gibt an, ob Sie den Hostnamen mit DNS überprüfen 
|===
Sie erstellen Regeln auf der Registerkarte Regeln für die automatische Auflösung. Die folgenden Schritte beschreiben den Prozess zur Regelerstellung.

.Verfahren
. Klicken Sie Auf *Verwalten > Geräteauflösung*
. Klicken Sie auf der Registerkarte *Regeln zur automatischen Auflösung* auf *+ Hostregel* oder *+ Bandregel*.
+
Der Bildschirm *Auflösungsregel* wird angezeigt.

+

NOTE: Klicken Sie auf den Link _Matching Criteria_, um Hilfe zu erhalten und Beispiele zum Erstellen von regulären Ausdrücken zu erhalten.

. Wählen Sie in der Liste *Typ* das Gerät aus, das Sie identifizieren möchten.
+
Sie können _Host_ oder _Band_ auswählen.

. Wählen Sie in der Liste *Quelle* die Quelle aus, mit der Sie den Host identifizieren möchten.
+
Je nach gewählter Quelle wird Cloud Insights die folgende Antwort angezeigt:

+
.. *Zonen* listet die Zonen und WWN auf, die von Cloud Insights identifiziert werden müssen.
.. *SRM* listet die nicht identifizierten Aliase auf, die von Cloud Insights identifiziert werden müssen
.. *Storage Alias* listet Storage-Aliase und WWN auf, die von Cloud Insights identifiziert werden müssen
.. *Alias wechseln* listet die Switch Aliase auf, die von Cloud Insights identifiziert werden müssen


. Wählen Sie in der Liste *Methode* die Methode aus, die Sie verwenden möchten, um den Host zu identifizieren.
+
|===


| Quelle | Methode 


| SRM | Wie ist, Trennzeichen, reguläre Ausdrücke 


| Storage-Alias | Trennzeichen, reguläre Ausdrücke 


| Alias wechseln | Trennzeichen, reguläre Ausdrücke 


| Zonen | Trennzeichen, reguläre Ausdrücke 
|===
+
** Für Regeln, die Trennzeichen verwenden, sind die Trennzeichen und die Mindestlänge des Hostnamens erforderlich. Die Mindestlänge des Host-Namens ist die Anzahl der Zeichen, die Cloud Insights zum Identifizieren eines Hosts verwenden sollte. Cloud Insights führt die DNS-Suche nur für Hostnamen durch, die so lange oder länger sind.
+
Bei Regeln, die Trennzeichen verwenden, wird die Eingabeszeichenfolge durch das Trennzeichen getokenisiert, und eine Liste von Hostnamenkandidaten wird durch das Erstellen mehrerer Kombinationen des benachbarten Tokens erstellt. Die Liste wird dann sortiert, die größte bis die kleinste. Für einen Eingabeerring von _vipsnq03_hba3_emc3_12ep0_ würde die Liste beispielsweise Folgendes ergeben:

+
*** Vipsnq03_hba3_emc3_12ep0
*** Vipsnq03_hba3_emc3
*** Hba3 emc3_12ep0
*** Vipsnq03_hba3
*** Emc3_12ep0
*** Hba3_emc3
*** Vipsnq03
*** 12ep0
*** Emc3
*** Hba3


** Regeln, die reguläre Ausdrücke verwenden, erfordern einen regulären Ausdruck, das Format und die Empfindlichkeitsauswahl für Fälle.


. Klicken Sie auf *Run AR*, um alle Regeln auszuführen, oder klicken Sie auf den Pfeil nach unten in der Schaltfläche, um die von Ihnen erstellte Regel (und alle anderen Regeln, die seit der letzten vollständigen Ausführung von AR erstellt wurden) auszuführen.
+
Die Ergebnisse des Regellaufs werden auf der Registerkarte * FC Identify* angezeigt.





== Starten einer automatischen Aktualisierung der Geräteauflösung

Ein Update zur Geräteauflösung setzt manuelle Änderungen fest, die seit der letzten vollständigen automatischen Gerätelaufauflösung hinzugefügt wurden. Das Ausführen eines Updates kann verwendet werden, um nur die neuen manuellen Einträge für die Konfiguration der Geräteauflösung zu übergeben und auszuführen. Es wird keine vollständige Gerätelaufauflösung durchgeführt.

.Verfahren
. Melden Sie sich in der Cloud Insights Web-UI an.
. Klicken Sie Auf *Verwalten > Geräteauflösung*
. Klicken Sie im Bildschirm *Geräteauflösung* auf den Pfeil nach unten in der Schaltfläche *Run AR*.
. Klicken Sie auf *Aktualisieren*, um die Aktualisierung zu starten.




== Regelgestützte manuelle Identifizierung

Diese Funktion wird für spezielle Fälle verwendet, in denen Sie eine bestimmte Regel oder eine Liste von Regeln (mit oder ohne einmalige Neuanordnung) ausführen möchten, um unbekannte Hosts, Speicher und Bandgeräte aufzulösen.

.Bevor Sie beginnen
Sie verfügen über eine Reihe von Geräten, die nicht identifiziert wurden, und Sie haben auch mehrere Regeln, die andere Geräte erfolgreich identifiziert haben.


NOTE: Wenn Ihre Quelle nur einen Teil eines Host- oder Gerätenamens enthält, verwenden Sie eine Regel für reguläre Ausdrücke, und formatieren Sie sie, um den fehlenden Text hinzuzufügen.

.Verfahren
. Melden Sie sich in der Cloud Insights Web-UI an.
. Klicken Sie Auf *Verwalten > Geräteauflösung*
. Klicken Sie auf die Registerkarte * Fibre Channel Identify*.
+
Das System zeigt die Geräte zusammen mit ihrem Auflösungsstatus an.

. Wählen Sie mehrere nicht identifizierte Geräte aus.
. Klicken Sie auf *Massenaktionen* und wählen Sie *Hostauflösung festlegen* oder *Bandauflösung festlegen*.
+
Das System zeigt den Identify-Bildschirm an, der eine Liste aller Regeln enthält, die Geräte erfolgreich identifiziert haben.

. Ändern Sie die Reihenfolge der Regeln in eine Bestellung, die Ihren Anforderungen entspricht.
+
Die Reihenfolge der Regeln wird im Identify-Bildschirm geändert, aber nicht global geändert.

. Wählen Sie die Methode aus, die Ihren Anforderungen entspricht.


Cloud Insights führt den Host-Auflösungsvorgang in der Reihenfolge aus, in der die Methoden angezeigt werden, beginnend mit den oben genannten.

Wenn geltende Regeln gefunden werden, werden in der Spalte Regeln Regelnamen angezeigt und als Handbuch identifiziert.

Verwandte Themen:link:task_device_resolution_fibre_channel.html["Fibre Channel-Geräteauflösung"]
link:task_device_resolution_ip.html["IP-Geräteauflösung"]
link:task_device_resolution_preferences.html["Einstellen Der Einstellungen Für Die Geräteauflösung"]
