---
sidebar: sidebar 
permalink: task_dc_emc_vplex.html 
keywords: data collector, VPLEX, EMC 
summary: Konfigurieren des VPLEX-Datensammlers. 
---
= Konfigurieren des EMC VPLEX-Datensammlers
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Performancedaten von EMC VPLEX-Speichersystemen. Zur Konfiguration benötigt der Datensammler eine IP-Adresse des VPLEX-Servers und ein Domain-Konto auf Administratorebene.


NOTE: Für die Performance-Erfassung durch VPLEX-Cluster von Cloud Insights muss der Performance-Archivierungsservice betriebsbereit sein, um die CSV-Dateien und Protokolle aufzufüllen, die Cloud Insights über SCP-basierte Dateikopien abruft. NetApp hat beobachtet, dass viele Updates der VPLEX-Firmware-Upgrades/Management Station diese Funktionen nicht mehr betriebsbereit machen werden. Kunden, die ein solches Upgrade planen, fragen Dell/EMC möglicherweise proaktiv, ob ihr geplantes Upgrade diese Funktion nicht mehr funktionsfähig bleibt. Wenn ja, wie kann sie die IT neu aktivieren, um Lücken bei der Performance-Sichtbarkeit zu minimieren? Der VPLEX-Performance-Code von Cloud Insight bewertet bei jeder Abfrage, ob alle erwarteten Dateien vorhanden sind und ob sie ordnungsgemäß aktualisiert werden. Wenn sie fehlen oder veraltet sind, protokolliert Cloud Insights Ausfälle bei der Performance-Erfassung.



== Terminologie

Cloud Insightst erwirbt die folgenden Bestandsinformationen vom VPLEX Data Collector. Für jeden erfassten Asset-Typ wird die am häufigsten für dieses Dokument verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Cluster | Storage 


| Motor | Storage-Node 


| Gerät, Systemumfang | Back-End Storage-Pool 


| Virtual Volume | Datenmenge 


| Front-End-Port, Back-End-Port | Port 


| Verteiltes Gerät | Storage-Synchronisierung 


| Übersicht Storage | Volume Map, Volume Mask 


| Storage Volume | Back-End LUN 


| ITLS | Back-End-Pfad 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Eine IP-Adresse der VPLEX Management Console
* Domänenkonto auf Administratorebene für den VPLEX-Server
* Port 443 (HTTPS): Erfordert eine ausgehende Verbindung zum TCP-Port 443 auf der VPLEX-Managementstation.
* Für die Leistung können Sie den schreibgeschützten Benutzernamen und das Kennwort für den ssh/scp-Zugriff verwenden.
* Für die Leistung ist Port 22 erforderlich.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| IP-Adresse der VPLEX Management Console | IP-Adresse oder vollqualifizierter Domänenname der VPLEX Management Console 


| Benutzername | Benutzername für VPLEX-CLI 


| Passwort | Passwort, das für die VPLEX-CLI verwendet wird 


| Remote-IP-Adresse für die Performance | Performance Remote IP-Adresse der VPLEX Management Console 


| Performance Remote User Name | Performance Remote-Benutzername der VPLEX Management Console 


| Kennwort Für Das Remote-Netzwerk Der Performance | Remote-Kennwort für die Performance der VPLEX Management Console 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Kommunikations-Port | Für VPLEX-CLI verwendeter Port. Der Standardwert ist 443. 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 20 Minuten. 


| Anzahl der Verbindungsversuche | Der Standardwert ist 3. 


| Leistungsintervall (Sek.) | Intervall zwischen Performance-Abstimmungen Der Standardwert beträgt 600 Sekunden. 


| Anzahl Wiederholungen | Der Standardwert ist 2. 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



==== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: Benutzerauthentifizierung fehlgeschlagen. | Stellen Sie sicher, dass Ihre Anmeldeinformationen für dieses Gerät korrekt sind. 
|===


==== Leistung

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| Fehler: VPLEX-Performance für Version unter 5.3 wird nicht unterstützt. | Aktualisieren Sie VPLEX auf 5.3 oder höher 


| Fehler: Es wurden nicht genügend Daten erfasst. | • Prüfen Sie den Zeitstempel der Sammlung in der Protokolldatei und ändern Sie das Abfrageintervall entsprechend • Warten Sie länger 


| Fehler: Unbefristete Log-Dateien werden nicht aktualisiert. | Wenden Sie sich an den EMC Support, um die Aktualisierung der unbefristeten Protokolldateien zu aktivieren 


| Fehler: Das Abfrageintervall für die Performance ist zu groß. | Überprüfen Sie den Sammlungs-Zeitstempel in der Protokolldatei €{logfile} und ändern Sie das Abfrageintervall entsprechend 


| Fehler: Performance Remote IP-Adresse der VPLEX Management Console ist nicht konfiguriert. | Bearbeiten Sie die Datenquelle, um die Performance Remote IP-Adresse der VPLEX Management Console festzulegen. 


| Fehler: Keine Leistungsdaten vom Director gemeldet | • Überprüfen Sie, ob die System-Performance-Monitore ordnungsgemäß ausgeführt werden • Bitte wenden Sie sich an den EMC Support, um die Aktualisierung der Protokolldateien des Systems Performance Monitor zu ermöglichen 
|===
Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
