---
sidebar: sidebar 
permalink: task_cs_user_management.html 
keywords: Cloud Secure, User, Login, account 
summary: Cloud Secure-Benutzerkonten werden über die Cloud Insights Benutzerverwaltung gemanagt 
---
= Benutzerverwaltung
:allow-uri-read: 


[role="lead"]
Cloud Secure-Benutzerkonten werden über Cloud Insights gemanagt.

Cloud Insights bietet vier Benutzerkontoebenen: Kontoinhaber, Administrator, Benutzer und Gast. Jedem Konto werden bestimmte Berechtigungsebenen zugewiesen. Ein Benutzerkonto mit Administratorrechten kann Benutzer erstellen oder ändern und jedem Benutzer eine der folgenden Cloud Secure-Rollen zuweisen:

|===


| Rolle | Cloud Secure Zugriff 


| Verwalter | Alle Cloud Secure-Funktionen, einschließlich der Funktionen für Alarme, Forensik, Datensammler, automatisierte Antwortrichtlinien und APIs für Cloud Secure, können ausgeführt werden. Ein Administrator kann auch andere Benutzer einladen, kann aber nur Cloud Secure-Rollen zuweisen. 


| Benutzer | Kann Warnungen anzeigen und verwalten und Forensik anzeigen. Benutzer können den Alarmstatus ändern, eine Notiz hinzufügen, Snapshots manuell erstellen und den Benutzerzugriff einschränken. 


| Gast | Kann Warnungen und Forensik anzeigen. Gastrolle kann den Alarmstatus nicht ändern, Notizen hinzufügen, Snapshots manuell erstellen oder den Benutzerzugriff einschränken. 
|===
.Schritte
. Melden Sie sich bei Cloud Secure an
. Klicken Sie im Menü auf *Admin > Benutzerverwaltung*
+
Sie werden zur Seite User Management von Cloud Insights weitergeleitet.

. Wählen Sie die gewünschte Rolle für jeden Benutzer aus.


Wählen Sie beim Hinzufügen eines neuen Benutzers einfach die gewünschte Rolle aus (normalerweise Benutzer oder Gast).

Weitere Informationen zu Benutzerkonten und Rollen finden Sie im Cloud Insights link:https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html["Benutzerrolle"] Dokumentation.
