---
sidebar: sidebar 
permalink: task_cs_delete_agent.html 
keywords: agent, Cloud Secure, delete agent 
summary: Cloud Secure-Agenten werden gelöscht 
---
= Löschen eines Cloud Secure-Agenten
:allow-uri-read: 


[role="lead"]
Wenn Sie einen Cloud Secure-Agenten löschen, müssen alle dem Agenten zugeordneten Datensammler zuerst gelöscht werden.



== Löschen eines Agenten


IMPORTANT: Durch das Löschen eines Agenten werden alle dem Agenten zugeordneten Datensammler gelöscht. Wenn Sie die Datensammler mit einem anderen Agenten konfigurieren möchten, sollten Sie vor dem Löschen des Agenten ein Backup der Data Collector-Konfigurationen erstellen.

.Bevor Sie beginnen
. Stellen Sie sicher, dass alle mit dem Agenten verknüpften Datensammler aus dem Cloud Secure-Portal gelöscht werden.
+
Hinweis: Ignorieren Sie diesen Schritt, wenn sich alle zugehörigen Kollektoren im STATUS „GESTOPPT“ befinden.



.Schritte zum Löschen eines Agenten:
. SSH in der Agent VM und führen Sie den folgenden Befehl aus. Wenn Sie dazu aufgefordert werden, geben Sie „y“ ein, um fortzufahren.
+
....
sudo /opt/netapp/cloudsecure/agent/install/cloudsecure-agent-uninstall.sh
Uninstall CloudSecure Agent? [y|N]:
....
. Klicken Sie Auf *Admin > Datensammler > Agenten*
+
Das System zeigt die Liste der konfigurierten Agenten an.

. Klicken Sie auf das Optionsmenü für den Agenten, den Sie löschen möchten.
. Klicken Sie Auf *Löschen*.
+
Das System zeigt die Seite *Agent löschen* an.

. Klicken Sie auf *Löschen*, um den Löschvorgang zu bestätigen.

