---
sidebar: sidebar 
permalink: task_dc_dell_xc_series.html 
keywords: data collector, Dell, EMC, xc 
summary: Konfigurieren des Dell EMC XC-Datensammlers. 
---
= Datensammler der Dell EMC XC-Serie
:allow-uri-read: 


[role="lead"]
Cloud Insights verwendet diesen Datensammler, um Bestands- und Performanceinformationen für die Dell EMC XC-Speicher-Arrays zu ermitteln.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Externe IP-Adresse des Prism | IP-Adresse des XC-Servers 


| Benutzername | Benutzername für den XC-Server 


| Passwort | Passwort, das für den XC-Server verwendet wird 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | Port, der für die TCP-Kommunikation mit dem XC-Server verwendet wird 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 60 Minuten. 


| Leistungsintervall (min) | Intervall zwischen Performance-Abstimmungen Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
