---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: Anmerkungen zur Unternehmenseinheit können zur Überwachung und Berichterstellung von Assets in Ihrer Unternehmenshierarchie verwendet werden 
---
= Anmerkungen Zur Geschäftseinheit
:allow-uri-read: 


[role="lead"]
Erstellen und verwalten Sie Geschäftseinheiten für Ihre Unternehmensumgebung mit dem Anmerkungstyp * Business Entity*.



== Erstellen einer Business-Einheit

Gehen Sie zum Erstellen einer Geschäftseinheit wie folgt vor:

. Klicken Sie auf *Verwalten > Anmerkungen* und dann auf den Link _Business Entity_.
+
Die Liste der aktuell definierten Geschäftseinheiten wird angezeigt.

. Klicken Sie Auf *+ Business Entity*.
. Geben Sie Werte für die Felder *Tenant*, *Line of Business*, *Business Unit* und *Project* ein.
+
Sie können jedes Feld leer lassen, wenn es nicht für Ihre Geschäftseinheit gilt.

. Wenn Sie zuvor einen Wert für ein Feld eingegeben haben, können Sie diesen Wert im Dropdown-Menü auswählen. Sie müssen es nicht erneut eingeben.



NOTE: Die ausgewählten Werte müssen eine eindeutige gesamte Geschäftseinheit bilden. Wenn Sie beispielsweise bereits eine Geschäftseinheit mit den Werten _A / B / C / D_ in dieser Reihenfolge haben, können Sie keine andere Geschäftseinheit mit diesen Werten in dieser Reihenfolge erstellen. Sie können jedoch eine Geschäftseinheit mit diesen Werten in einer anderen Reihenfolge erstellen.



== Anwenden einer Business-Einheit auf ein Objekt

Die einfachste Möglichkeit, eine Geschäftseinheit auf ein Objekt oder ein Objekt anzuwenden, besteht aus einer Abfrage.

. Klicken Sie auf *Abfragen > +Neue Abfrage* und wählen Sie den gewünschten Objekttyp aus. Sie können Filter anwenden, um die Ergebnisse weiter einzugrenzen.
. Aktivieren Sie das Kontrollkästchen, um die Objekte auszuwählen, für die Sie die Geschäftseinheit anwenden möchten.
. Klicken Sie auf *Massenaktionen* und wählen Sie *Anmerkung hinzufügen*.
. Wählen Sie die Anmerkung _Business Entity_ aus, und wählen Sie den gewünschten Wert für die Geschäftseinheit aus der Liste aus.
. Klicken Sie auf *Speichern*, um die Geschäftseinheit auf die Objekte anzuwenden.


Sie können eine Geschäftseinheit auch auf ein einzelnes Objekt anwenden, indem Sie zur Asset-Landing-Page des Objekts navigieren und im Bereich Benutzerdaten auf *+Annotation klicken.

Sie können auch ein konfigurieren link:task_create_annotation_rules.html["Anmerkungsregel"] So wenden Sie Business Entities auf Objekte an.


NOTE: Einem Objekt kann nur eine Geschäftseinheit zugeordnet sein.



== Entfernen einer Business-Einheit aus einem Objekt

Um eine Business-Entity aus einem Objekt oder einem Objekt zu entfernen, wählen Sie die Objekte aus, klicken Sie auf *Massenaktionen* und wählen Sie _Anmerkung entfernen_. Wählen Sie die Anmerkung Business Entity aus, und klicken Sie auf *Löschen*.
