---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: Melden Sie sich für Cloud Insights an und erstellen Sie Ihre Umgebung. 
---
= Cloud Insights-Onboarding
:allow-uri-read: 


[role="lead"]
Bevor Sie mit der Cloud Insights arbeiten können, müssen Sie sich im Portal *NetApp Cloud Central* anmelden. Wenn Sie bereits über eine Anmeldung bei NetApp Cloud Central verfügen, können Sie mit wenigen schnellen Schritten eine kostenlose Testversion von Cloud Insights starten.


toc::[]


== Erstellen Ihres NetApp Cloud Central Kontos

Unter können Sie sich anmelden, um auf die Cloud-Services von NetApp zuzugreifen https://cloud.netapp.com["*NetApp Cloud Central*"^] Und klicken Sie auf *Registrieren*.

* Geben Sie eine gültige geschäftliche E-Mail-Adresse ein und wählen Sie ein Passwort.
* Geben Sie Ihren Firmennamen und Ihren vollständigen Namen ein.
* Akzeptieren Sie die Allgemeinen Geschäftsbedingungen und klicken Sie auf *Registrieren*.


Anschließend gelangen Sie zu den Cloud-Angeboten von NetApp.

Wählen Sie Cloud Insights.



=== Was ist, wenn ich bereits einen NetApp Cloud Login habe?

Wenn Sie bereits über einen NetApp Cloud Central Account verfügen, wählen Sie einfach *Anmelden* auf der https://cloud.netapp.com["*NetApp Cloud Central*"^] Portalseite.

Geben Sie Ihre E-Mail-Adresse und Ihr Kennwort ein. Anschließend gelangen Sie zu den Cloud-Angeboten von NetApp.

Wählen Sie Cloud Insights.



== Starten Sie Ihren Cloud Insights kostenlosen Test

Wenn Sie sich zum ersten Mal bei Cloud Insights anmelden, klicken Sie unter dem Cloud Insights-Angebot auf *Kostenlose Testversion starten*. Cloud Insights wird dann die Umgebung Ihres Unternehmens erstellen.

Sobald die Erstellung Ihrer Umgebung abgeschlossen ist, können Sie sich mit Ihren Zugangsdaten für Cloud Central anmelden und die kostenlose 30-Tage-Testversion von Cloud Insights starten. Während dieser Testversion können Sie sich alle Funktionen der Cloud Insights Standard Edition ansehen.

Während der kostenlosen Testversion können Sie dies gerne link:concept_subscribing_to_cloud_insights.html["Starten Sie Ihr Abonnement"] Cloud Insights zu jeder Zeit. Wenn Sie abonniert haben, können Sie die Cloud Insights-Funktionen auf Grundlage Ihrer aktuellen Subscription verwenden.



== Melden Sie sich an und gehen Sie

Sobald Ihr Mandant erstellt wurde, können Sie sich jederzeit einfach im NetApp Cloud Portal anmelden und auf *Gehe zu Cloud Insights* klicken. Sie werden direkt in Ihre Cloud Insights Umgebung gebracht.

Sie können einen Browser auch direkt auf Ihrer URL für die Cloud Insights-Umgebung öffnen, beispielsweise:

 https://<environment-name>.c01.cloudinsights.netapp.com/
Die URL wird auch in die Einladungs-E-Mail jedes Benutzers für einfachen Zugriff und Lesezeichen enthalten. Wenn der Benutzer nicht bereits bei Cloud Central angemeldet ist, werden diese zur Anmeldung aufgefordert.


NOTE: Neue Benutzer müssen sich trotzdem für den Zugriff auf Cloud Central anmelden, bevor sie auf ihre Umgebung-URL zugreifen können.

Wenn Sie sich zum ersten Mal in einer neuen Umgebung anmelden, werden Sie durch die Einrichtung bis geleitet link:task_getting_started_with_cloud_insights.html["*Datensammlung beginnen*"].



== Abmelden

Um sich von Cloud Insights abzumelden, klicken Sie auf Ihren *Benutzername* und wählen *Abmelden*. Sie gelangen zurück zum Anmeldebildschirm von Cloud Central.


NOTE: Wenn Sie sich von Cloud Insights abmelden, melden Sie sich von Cloud Central ab. Außerdem werden Sie von anderen NetApp Cloud-Services abgemeldet, die das Cloud Central-Anmeldezeichen verwenden.
