---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'Konfiguration des Datensammlers HP Enterprise Alletra 6000 (ehemals Nimble).' 
---
= HPE Alletra 6000 Datensammler
:allow-uri-read: 


[role="lead"]
Der HP Enterprise Alletra 6000 (vormals Nimble) Datensammler unterstützt Bestands- und Performancedaten von Alletra 6000 Storage Arrays.



== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen von diesem Sammler. Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Array Erledigen | Storage 


| Festplatte | Festplatte 


| Datenmenge | Datenmenge 


| Pool | Storage-Pool 


| Initiator | Storage-Host-Alias 


| Controller | Storage-Node 


| Fibre Channel-Schnittstelle | Controller 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

Zum Erfassen von Bestands- und Konfigurationsdaten aus dem Speicher-Array müssen Sie Folgendes haben:

* Das Array muss installiert und konfiguriert sein und über den Client über seinen vollständig qualifizierten Domänennamen (FQDN) oder die Array-Management-IP-Adresse erreichbar sein.
* Auf dem Array muss NimbleOS 2.3.x oder höher ausgeführt werden.
* Sie müssen einen gültigen Benutzernamen und ein Kennwort für das Array mit der Rolle „Operator“ besitzen. Die „Gast“-Rolle verfügt nicht über ausreichenden Zugriff, um Initiator-Konfigurationen zu verstehen.
* Port 5392 muss auf dem Array geöffnet sein.


Zum Erfassen von Performance-Daten aus dem Speicher-Array müssen Sie Folgendes haben:

* Auf dem Array muss NimbleOS 4.0.0 oder höher ausgeführt werden
* Für das Array müssen Volumes konfiguriert sein. Die einzige Performance API NimbleOS hat sich für Volumes entwickelt, und alle Statistiken Cloud Insights Berichte wurden aus den Statistiken zu Volumes abgeleitet




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Array-Management-IP-Adresse | Vollständig qualifizierter Domain-Name (FQDN) oder Array-Management-IP-Adresse. 


| Benutzername | Benutzername für das Array 


| Passwort | Kennwort für das Array 
|===


== Erweiterte Konfiguration

|===


| Feld | Beschreibung 


| Port | Der von Nimble REST API verwendete Port. Der Standardwert ist 5392. 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 60 Minuten. 
|===
Hinweis: Das Standard-Performance-Abfrageintervall beträgt 300 Sekunden und kann nicht geändert werden. Dies ist das einzige von HPE Alletra 6000 unterstützte Intervall.
