---
sidebar: sidebar 
permalink: task_research_failed_collector.html 
keywords: data collector, changes, failures 
summary: Fehler beim Datensammler 
---
= Recherchieren eines fehlgeschlagenen Datensammlers
:allow-uri-read: 


[role="lead"]
Wenn ein Datensammler über eine Fehlermeldung und eine hohe oder mittlere Auswirkung verfügt, müssen Sie dieses Problem anhand der Datensammler-Übersichtsseite mit den verknüpften Informationen untersuchen.

Gehen Sie wie folgt vor, um die Ursache für fehlgeschlagene Datensammler zu ermitteln. Fehlermeldungen der Datensammler werden im Menü *Admin* und auf der Seite *installierte Datensammler* angezeigt.

.Schritte
. Klicken Sie Auf *Admin* > *Datensammler* > *Installierte Datensammler*.
. Klicken Sie auf den verknüpften Namen des defekten Datensammlers, um die Seite Zusammenfassung zu öffnen.
. Auf der Seite Zusammenfassung können Sie im Bereich Kommentare alle Hinweise lesen, die von einem anderen Techniker hinterlassen wurden, der möglicherweise auch diesen Fehler untersucht hat.
. Notieren Sie alle Leistungsmeldungen.
. Bewegen Sie den Mauszeiger über die Segmente des Ereigniskleistendiagramms, um zusätzliche Informationen anzuzeigen.
. Wählen Sie eine Fehlermeldung für ein Gerät aus, die unter der Ereigniszeitleiste angezeigt wird, und klicken Sie auf das Symbol Fehlerdetails rechts neben der Meldung.
+
Die Fehlerdetails enthalten den Text der Fehlermeldung, die wahrscheinlichsten Ursachen, die verwendeten Informationen und Vorschläge, was versucht werden kann, das Problem zu beheben.

. Im Bereich Geräte, die von diesem Data Collector gemeldet werden, können Sie die Liste filtern, um nur Geräte von Interesse anzuzeigen. Sie können dann auf den verknüpften *Name* eines Geräts klicken, um die Asset-Seite für dieses Gerät anzuzeigen.
. Wenn Sie zur Übersichtsseite des Datensammlers zurückkehren, überprüfen Sie im Bereich *Letzte Änderungen anzeigen* unten auf der Seite, um zu sehen, ob die letzten Änderungen das Problem verursacht haben könnten.

