---
sidebar: sidebar 
permalink: task_config_cs_data_collectors.html 
keywords: acquisition, AU, data collector, collector 
summary: Konfigurieren Sie Datensammler 
---
= Konfigurieren Von Datensammlern
:allow-uri-read: 


[role="lead"]
Sie konfigurieren Datensammler in Ihrer Cloud Insights-Umgebung, um Daten von Hosts, Services oder Geräten im Datacenter zu erfassen.

.Bevor Sie beginnen
* Sie müssen über Account Owner oder Admin-Berechtigungen verfügen, um Datensammler zu konfigurieren.
* Sie müssen eine Akquisitionseinheit (für Infrastrukture) oder einen Agenten (für Services oder Hosts) konfiguriert haben, bevor Sie mit dem Sammeln von Daten beginnen können.
* Sie benötigen Zugangsdaten für die Infrastrukturgeräte, von denen Sie Daten erfassen.
+
Für alle Geräte, von denen Sie Daten sammeln möchten, sind Netzwerkadressen, Kontoinformationen und Passwörter erforderlich.





=== Sicherheit Für Anmeldeinformationen

Die Daten-Collector-Anmeldeinformationen werden verschlüsselt, wenn sie in Cloud Insights eingegeben werden. Sie werden zuerst durch den öffentlichen Schlüssel der AU verschlüsselt und dann über HTTPS verschlüsselt an die Acquisition Unit (AU) gesendet. Verschlüsselte Werte werden entschlüsselt, wenn die AU sie zur Kommunikation mit Geräten und Software verwendet.



=== Konfigurieren des Data Collectors

* Klicken Sie im Menü Cloud Insights auf *Admin > Datensammler* und klicken Sie auf die Schaltfläche *+ Data Collector*. Sie können alle Datensammler anzeigen oder filtern, um nur die Datensammler anzuzeigen, die Ihnen auf Grundlage Ihres Abonnements zur Verfügung stehen.


* Je nach gewähltem Datensammlungstyp variieren die Installationsschritte.




==== Betriebssysteme:

Sie müssen mindestens einen Cloud Insights Agent installieren, um mit dem Erfassen von Betriebssystem- oder Servicedaten aus Ihrer Umgebung zu beginnen. Sie können so viele Agenten installieren, wie Sie möchten. Jeder Agent kann Daten aus mehreren Services erfassen.

Zusätzlich zum Erfassen von Daten aus Services fungiert jeder Agent auch als Datensammler für die VM/den Host, auf dem er installiert ist. Die erfassten Daten werden als „Knoten“-Daten in Dashboard-Widgets oder Abfragen dargestellt.

. Klicken Sie auf den Plattformtyp oder das Betriebssystem der VM oder des Hosts (d. h. auf den Knoten), von dem aus Sie auf Cloud Insights zugreifen.
. Wählen Sie einen Agent-Zugriffsschlüssel aus.
. Den angezeigten Befehl in die Zwischenablage kopieren. Sie können auf das Clipboard-Symbol klicken, um den Befehl schnell zu kopieren.
. Öffnen Sie in der Agent-VM/Host ein Terminal/Befehlsfenster, und fügen Sie den Befehl ein. Drücken Sie die Eingabetaste, um den Befehl auszuführen.
. Klicken Sie nach der Installation des Agenten auf *Fertig stellen*. Der Agent beginnt mit dem Erfassen von Daten.
+
Es kann bis zu zwei Abfragezeiten dauern, bis die Daten für den Knoten in Dashboards angezeigt oder für die Abfrage verfügbar sind.





==== Dienste:

Services Data Collectors basieren auf dem telegraf-Agent, wie z. B. Docker oder Kibana.

.Bevor Sie beginnen
* Sie benötigen mindestens einen Cloud Insights-Agent, um Servicedaten aus Ihrer Umgebung zu erfassen. Wenn kein Agent installiert ist, werden Sie aufgefordert, einen zu installieren, wenn Sie einen Service Data Collector konfigurieren.
* Der Service, von dem Sie Daten erfassen möchten, muss in Ihrer Umgebung installiert und in Betrieb sein.
+
.. Klicken Sie auf einen Datensammler Dienste.
.. Wählen Sie ein Agent-Betriebssystem oder eine Plattform. Wenn Sie keinen Agent für die Plattform installiert haben, befolgen Sie dazu die Anweisungen.
.. Wählen Sie einen Agent-Zugriffsschlüssel aus.
.. Klicken Sie Auf *Weiter*.
.. Befolgen Sie die Anweisungen zur Konfiguration des Datensammlers. Sie können auf das Clipboard-Symbol klicken, um die angezeigten Befehle oder Codeschnipsel schnell zu kopieren.
.. Wenn der Datensammler richtig konfiguriert ist, klicken Sie auf *Fertig stellen*.
+
Es kann bis zu zwei Abfrageperioden dauern, bis die Daten aus dem Dienst in Dashboards angezeigt oder für die Abfrage verfügbar sind.







==== Infrastruktur:

Infrastrukturdatensammler umfassen beispielsweise Storage oder Switches.

.Bevor Sie beginnen
* Sie müssen mindestens eine Erfassungseinheit konfiguriert haben, um mit dem Erfassen von Infrastrukturdaten zu beginnen.
+
.. Klicken Sie auf einen Infrastructure Data Collector.
.. Geben Sie einen Namen für den Datensammler ein. Namen dürfen die folgenden Zeichen enthalten:


* Buchstabe (a-z)
* Zahl (0-9)
* Bindestrich (-)
* Unterstrich (_)
* Periode (.)
* Leerzeichen ( )
+
Namen dürfen nicht mit Leerzeichen, Punkt oder Bindestrich beginnen oder enden.

+
.. Geben Sie die Erfassungseinheit ein, die diesem Datensammler zugeordnet werden soll.
.. Geben Sie die erforderlichen Felder im Konfigurationsbildschirm ein.
.. Klicken Sie auf *Erweiterte Konfiguration*, um weitere Konfigurationsfelder einzugeben. Nicht alle Datensammler benötigen erweiterte Konfiguration.
.. Klicken Sie auf *Testkonfiguration*, um zu überprüfen, ob der Datensammler ordnungsgemäß konfiguriert ist.
.. Klicken Sie anschließend auf *Collector hinzufügen*.




Hilfe zum Hinzufügen einer neuen Erfassungseinheit finden Sie unter link:task_configure_acquisition_unit.html["Konfigurieren von Akquisitionseinheiten"]

+ Es kann bis zu zwei Abfrageperioden dauern, bevor Daten aus der Umgebung in Dashboards angezeigt oder zur Abfrage verfügbar sind.
