---
sidebar: sidebar 
permalink: task_config_cs_amazon_fsx.html 
keywords: Cloud, Storage, AWS, Fsx 
summary: Cloud Secure verwendet Datensammler, um Datei- und Benutzerzugriffsdaten von Geräten zu erfassen. 
---
= Konfiguration von Amazon FSX für NetApp ONTAP
:allow-uri-read: 


[role="lead"]
Dieser Datensammler sammelt Datei- und Benutzerdaten von Amazon FSX für NetApp ONTAP. Dieser Datensammler wird schrittweise in allen Cloud Insights-Servicegebieten zur Verfügung gestellt. Wenden Sie sich an Ihren Vertriebsmitarbeiter, wenn das Symbol für diesen Sammler in Ihrer Cloud Insights-Umgebung nicht angezeigt wird.



=== Agent-Gerätekonfiguration

Konfigurieren Sie die Maschine, die als Cloud Secure-Agent verwendet werden soll, mit den folgenden Schritten:

. Melden Sie sich bei der AWS Konsole an, navigieren Sie zur Seite EC2-instances, und wählen Sie Launch Instance aus.
. Wählen Sie eine RHEL- oder CentOS AMI-Version mit der entsprechenden Version aus, wie in erwähnt link:concept_cs_agent_requirements.html["Anforderungen"].
. Erstellen Sie das Feld Agent in derselben VPC und demselben Subnetz, in dem sich die Amazon FSX für die NetApp ONTAP Instanz befindet.
+
Oder die Box „Agent“ sollte in einer VPC liegen, die mit der Amazon FSX für NetApp ONTAP VPC verbunden ist.

+
Vergewissern Sie sich, dass bidirektionale Kommunikation zwischen dem Agent und Amazon FSX für NetApp ONTAP vorhanden ist.

. Wählen Sie t2.xlarge (4 vcpus und 16 GB RAM) als zugewiesene Ressourcen aus.
+
.. Erstellen Sie die EC2-Instanz.


. Installieren Sie die erforderlichen Linux-Pakete mithilfe des YUM-Paketmanagers:
+
.. Installieren Sie wget und entzip native Linux-Pakete.






=== Installieren Sie den Cloud Secure Agent

. Melden Sie sich als Administrator oder Account-Inhaber in Ihrer Cloud Insights-Umgebung an.
. Navigieren Sie zu Cloud Secure Admin > Data Collectors, und klicken Sie auf die Registerkarte Agents.
. Klicken Sie auf +Agent und geben Sie RHEL als Zielplattform an.
. Kopieren Sie den Befehl Agenteninstallation.
. Fügen Sie den Befehl „Agent Installation“ in die RHEL EC2-Instanz ein, bei der Sie angemeldet sind.
+
Dadurch wird der Cloud Secure-Agent installiert, sofern alle Agent-Voraussetzungen erfüllt sind.



Ausführliche Schritte finden Sie im Cloud Secure link:task_cs_add_agent.html["Agenteninstallation"] Seite,
