---
sidebar: sidebar 
permalink: task-configure-placement-group-failure-aws.html 
keywords: placement group, failure, HA single zone, app.conf, rollback, AWS 
summary: Für Verbindungen zu den zugehörigen Storage-Konten nutzt Cloud Volumes ONTAP einen Azure Private Link. Bei Bedarf können Sie Azure Private Links deaktivieren und stattdessen Service-Endpunkte verwenden. 
---
= Konfiguration der Erstellung von Platzierungsgruppen für AWS HA Single AZ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP fällt aus und führt neue Implementierungen der AWS HA-Konfigurationen (High Availability, Hochverfügbarkeit) in einer einzelnen Verfügbarkeitszone (AZ) zurück, sobald die Erstellung der Speichergruppen ausfällt. Bei Bedarf können Sie den erfolgreichen Abschluss von Bereitstellungen erzwingen, indem Sie Platzierungsgruppen so konfigurieren, dass der Rollback-Prozess bei jedem Fehler der Erstellung umgehen kann.



== Überblick

Standardmäßig werden Implementierungen fehlschlagen und Rollback durchgeführt, wenn eine Platzierungsgruppe den Erstellungsvorgang für eine einzige HA-Verfügbarkeitszone in der Arbeitsumgebung nicht unterstützt. Die Erstellung der Platzierungsgruppe schlägt ebenfalls fehl und führt ein Rollen zurück, wenn sowohl Cloud Volumes ONTAP-Nodes als auch die Instanz des Mediators nicht vorhanden sind.

Sie können den Rollback-Prozess umgehen, wenn die Erstellung der Platzierungsgruppe fehlschlägt und die Bereitstellung durch die Konfiguration der Datei App.conf fortgesetzt werden kann. Beim Umgehen des Rollback-Prozesses wurden die Bereitstellungen erfolgreich abgeschlossen, und das System generiert eine Benachrichtigung, die besagt, dass die Erstellung der Platzierungsgruppe fehlgeschlagen ist und der Status unvollständig ist.



=== Deaktivieren des Rollbacks bei Ausfall der Platzierungsgruppe

Um den Ausfall der Platzierungsgruppe zu deaktivieren, muss das Flag „Rollback-on-placement-Group-Failure“ auf „false“ gesetzt werden.

.Schritte
. Verwenden Sie SSH, um eine Verbindung zum Connector-Host herzustellen und sich anzumelden.
. Navigieren Sie zum folgenden Verzeichnis: /Opt/Application/netapp/cloudmanager/docker_occm/Data
. Bearbeiten Sie App.conf, indem Sie den Wert für den Parameter „Rollback-on-placement-Group-failure“ in „false“ ändern:
+
[listing]
----
{
    "occm" : {
        "aws" : {
            "rollback-on-placement-group-failure" : false
        }
    }
}
----
+

NOTE: Standardmäßig ist der Parameter „Rollback-on-placement-Group-Failure“ auf „true“ gesetzt.

. Speichern Sie die Datei und melden Sie sich vom Connector ab.
+
Ein Neubooten ist nicht erforderlich.


