---
sidebar: sidebar 
permalink: task_dc_hds_ops_center.html 
keywords: data collector, Hitachi Ops Center 
summary: Konfiguration des HDS cops Center Datensammlers 
---
= Datensammler Hitachi Ops Center
:allow-uri-read: 


[role="lead"]
Dieser Datensammler verwendet die integrierte Anwendungssuite von Hitachi Ops Center, um auf Bestands- und Performancedaten mehrerer Speichergeräte zuzugreifen.



== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen von diesem Datensammler. Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Storage-Systeme | Storage 


| Datenmenge | Datenmenge 


| Paritätsgruppen | Speicherpool (RAID), Festplattengruppen 


| Festplatte | Festplatte 


| Storage-Pool | Speicherpool (Thin, SNAP) 


| Externe Paritätsgruppen | Speicherpool (Backend), Festplattengruppen 


| Port | Storage-Node → Controller-Node →-Port 


| Host-Gruppen | Volume-Zuordnung und -Maskierung 


| Volume-Paare | Storage-Synchronisierung 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Inventaranforderungen

Zur Erfassung von Bestandsdaten müssen Sie Folgendes haben:

* IP-Adresse des Ops Center-Servers
* Schreibgeschützter Benutzername und Kennwort für die Ops Center-Software und Peer-Berechtigungen




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Hitachi Ops Center-IP-Adresse | IP-Adresse oder vollqualifizierter Domain-Name des Ops Center Servers 


| Benutzername | Benutzername für den Ops-Center-Server. 


| Passwort | Passwort, das für den Ops-Center-Server verwendet wird. 
|===


== Erweiterte Konfiguration

|===


| Feld | Beschreibung 


| Verbindungstyp | HTTPS (Port 443) ist der Standard 


| TCP-Port überschreiben | Geben Sie den zu verwendenden Port an, wenn nicht der Standardport 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 40. 


| Wählen Sie „Ausschließen“ oder „Einschließen“, um eine Liste anzugeben | Geben Sie an, ob die unten aufgeführte Array-Liste beim Sammeln von Daten aufgenommen oder ausgeschlossen werden soll. 


| Geräteliste filtern | Kommagetrennte Liste der Geräte-IDs oder Array-Namen, die einbezogen oder ausgeschlossen werden sollen 


| Leistungsintervall (Sek.) | Intervall zwischen Performance-Abstimmungen Der Standardwert ist 300. 
|===
Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
