---
sidebar: sidebar 
permalink: task_dc_openstack.html 
keywords: data collector, openstack, OpenStack 
summary: OpenStack Data Collector, 
---
= OpenStack Data Collector
:allow-uri-read: 


[role="lead"]
Der OpenStack (REST API/KVM) Data Collector erfasst Bestandsdaten für alle OpenStack Instanzen und optional VM-Performance-Daten.



== Anforderungen

* IP-Adresse des OpenStack Controllers
* Anmeldeinformationen für OpenStack Admin-Rollen und Zugriff auf den Linux-KVM-Hypervisor. Wenn Sie das Administratorkonto oder die entsprechenden Administratorrechte nicht verwenden, müssen Sie die Standardrichtlinien mithilfe von „Trial and Error“ ermitteln, um sich für Ihre Benutzer-ID für Datensammler zu entspannen.
* Das OpenStack Ceilometer-Modul muss für die Performance-Erfassung installiert und konfiguriert sein. Die Konfiguration des Ceilometers erfolgt durch Bearbeiten der Nova.conf-Datei für jeden Hypervisor und dann durch Neustart des Nova Compute Service auf jedem Hypervisor. Die Optionsnamen ändern sich für verschiedene OpenStack Versionen:
+
** Icehouse
** Juno
** Kilo
** Freiheit
** Mitaka
** Newton
** Kata


* Für CPU-Statistiken muss „Compute_Monitors=ComputeDriverCPUMonitor“ in /etc/Nova/Nova.conf auf Computing-Knoten eingeschaltet werden.
* Port-Anforderungen:
+
** 5000 für http und 13000 für https, für den Keystone Service
** 22 für KVM SSH
** 8774 für Nova Compute Service
** 8776 für Cinder Block Service
** 8777 für den Ceilometer Performance Service
** 9292 für Glance Image Service *Hinweis* der Port bindet sich an den spezifischen Dienst, und der Dienst kann auf dem Controller oder einem anderen Host in größeren Umgebungen ausgeführt werden.






== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| OpenStack-Controller-IP-Adresse | IP-Adresse oder vollqualifizierter Domain-Name des OpenStack Controllers 


| OpenStack Administrator | Benutzername für einen OpenStack Admin 


| OpenStack Passwort | Passwort, das für den OpenStack Admin verwendet wird 


| OpenStack Administrator-Mandant | Mandantenname des OpenStack Administrator 


| KVM-Sudo-Benutzer | KVM sudo Benutzername 


| Wählen Sie „Kennwort“ oder „OpenSSH-Schlüsseldatei“, um den Anmeldeinformationstyp anzugeben | Anmeldeinformationstyp, der für die Verbindung zum Gerät über SSH verwendet wird 


| Vollständiger Pfad zum privaten Bestandsschlüssel | Vollständiger Pfad zum privaten Bestandsschlüssel 


| KVM-Sudo-Kennwort | KVM-Sudo-Kennwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Aktivieren der Erkennung des Hypervisor-Inventars über SSH | Aktivieren Sie diese Option, um die Erkennung des Hypervisor-Inventars über SSH zu aktivieren 


| OpenStack Admin-URL-Port | OpenStack Admin-URL-Port 


| Verwenden Sie HTTPS | Überprüfen Sie, ob sicheres HTTP verwendet wird 


| SSH-Port | Port, der für SSH verwendet wird 


| SSH-Prozess wird erneut ausgeführt | Anzahl der Versuche für einen erneuten Versuch in der Bestandsaufnahme 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 20 Minuten. 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



==== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| „Konfigurationsfehler“ mit Fehlermeldungen beginnen mit „Policy lässt nicht zu“ oder „Sie sind nicht autorisiert“ | * ip-Adresse prüfen * Benutzername und Passwort überprüfen 
|===
Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
