---
sidebar: sidebar 
permalink: task_dc_pure_flasharray.html 
keywords: data collector, Pure Storage, pure 
summary: Pure Storage Data Collector wird konfiguriert. 
---
= Datensammler Pure Storage FlashArray
:allow-uri-read: 


[role="lead"]
Cloud Insights erfasst mithilfe des Datensammlers Pure Storage FlashArray Bestands- und Performance-Daten.



== Terminologie

Für jeden von Cloud Insights erfassten Asset-Typ wird die am häufigsten für die Ressource verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Laufwerk (SSD) | Festplatte 


| Array Erledigen | Storage 


| Controller | Storage-Node 


| Datenmenge | Datenmenge 


| LUN-Zuordnung | Volume-Zuordnung 


| Initiator, Ziel | Volume-Maske 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* IP-Adresse des Storage-Systems
* Benutzername und Kennwort für das Administratorkonto des Pure Storage-Systems.
* Port-Anforderung: HTTP/HTTPS 80/443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| FlashArray Host-IP-Adresse | IP-Adresse des Storage-Systems 


| Benutzername | Benutzername mit Administratorrechten 


| Passwort für das Administratorkonto | Passwort 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Verbindungstyp | Wählen Sie HTTP oder HTTPS. Zeigt auch den Standardport an. 


| TCP-Port überschreiben | Wenn Sie leer sind, verwenden Sie den Standardport im Feld Verbindungstyp. Andernfalls geben Sie den zu verwendenden Anschluss ein 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 60 Minuten 


| Leistungsintervall (Sek.) | Der Standardwert ist 300 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



==== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| „Ungültige Anmeldeinformationen“ mit Fehlermeldungen „Richtlinie lässt nicht zu“ oder „Sie sind nicht autorisiert“ | Validierung des Pure Benutzerkontos und Passworts über die Pure http Schnittstelle 
|===
Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
