---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Konfigurieren VON DELL EMC RecoverPoint Data Collector 
---
= Dell EMC RecoverPoint Data Collector
:allow-uri-read: 


[role="lead"]
Der EMC RecoverPoint Data Collector sammelt Bestandsdaten vom EMC RecoverPoint-Speicher. Zur Konfiguration benötigt der Datensammler die IP-Adresse der Speicherprozessoren sowie einen schreibgeschützten Benutzernamen und ein Kennwort.

Der EMC RecoverPoint Data Collector sammelt die Replikationsbeziehungen zwischen Volume und Volume, die RecoverPoint über andere Speicher-Arrays hinweg koordiniert. Cloud Insights zeigt für jedes RecoverPoint-Cluster ein Speicher-Array an und sammelt Bestandsdaten für Knoten und Speicherports auf diesem Cluster. Es werden keine Storage-Pool- oder Volume-Daten erfasst.



== Anforderungen

Zur Konfiguration dieses Datensammlers sind folgende Informationen erforderlich:

* IP-Adresse oder vollqualifizierter Domain-Name des Speicherprozessors
* Schreibgeschützter Benutzername und Kennwort
* REST-API-Zugriff über Port 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Adresse von RecoverPoint | IP-Adresse oder vollqualifizierter Domain-Name des RecoverPoint-Clusters 


| Benutzername | Benutzername für das RecoverPoint-Cluster 


| Passwort | Passwort, das für den RecoverPoint-Cluster verwendet wird 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port für die Verbindung mit dem RecoverPoint-Cluster 


| Abfrageintervall für Bestand (Minuten) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 20 Minuten. 


| Ausgeschlossene Cluster | Kommagetrennte Liste von Cluster-IDs oder Namen, die beim Abfragen ausgeschlossen werden sollen. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
