---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: Konfigurieren des IBM Cleversafe Datensammlers. 
---
= IBM Cleversafe Datensammler
:allow-uri-read: 


[role="lead"]
Cloud Insights verwendet diese Datensammlung, um Bestands- und Performancedaten für IBM Cleversafe Speichersysteme zu ermitteln.



== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen vom IBM Cleversafe Datensammler. Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Storage-Pool | Storage-Pool 


| Container | Internes Volumen 


| Container | Dateifreigabe 


| NFS-Share | Share 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Die IP-Adresse für externe Datendienste für den Cluster
* Administrator-Benutzername und -Passwort
* Port 9440




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Manager-IP oder Host-Name | IP-Adresse oder Hostname des Management-Node 


| Benutzername | Benutzername für das Benutzerkonto mit Superuser- oder Systemadministrator-Rolle 


| Passwort | Kennwort für das Benutzerkonto mit Superuser- oder Systemadministrator-Rolle 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen 


| HTTP-Verbindungszeitlimit (Sek.) | HTTP-Zeitüberschreitung in Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
