---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Konfigurieren von Infiniat InfiniBox Datensammler. 
---
= Infiniat InfiniBox Datensammler
:allow-uri-read: 


[role="lead"]
Der Datensammler Infinibei InfiniBox (HTTP) wird verwendet, um Inventarinformationen vom Infiniat InfiniBox-Speichersystem zu sammeln.



== Terminologie

Cloud Insights erwirbt folgende Bestandsinformationen vom Datensammler Infiniat InfiniBox. Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Storage-Pool | Storage-Pool 


| Knoten | Controller 


| Dateisystem | Internes Volumen 


| Dateisystem | Dateifreigabe 


| Dateisystem-Exporte | Share 
|===


== Anforderungen

Die folgenden Anforderungen gelten für die Konfiguration dieses Datensammlers.

* IP-Adresse oder FQDN des InfiniBox-Managementknoten
* Admin-Benutzer-ID und Passwort
* Port 443 über REST API




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| InfiniBox Host | IP-Adresse oder vollqualifizierter Domainname des InfiniBox Management Node 


| Benutzername | Benutzername für InfiniBox Management Node 


| Passwort | Passwort für den InfiniBox Management-Knoten 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port zur Verbindung mit InfiniBox-Server. Der Standardwert ist 443. 


| Abfrageintervall Für Bestand | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 60 Minuten. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
