---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Nutanix Datensammler wird konfiguriert. 
---
= Nutanix NX-Datensammler
:allow-uri-read: 


[role="lead"]
Cloud Insights ermittelt mit dem Nutanix Datensammler Bestands- und Performance-Daten für Nutanix NX Storage-Systeme.



== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen vom Nutanix Data Collector, Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Storage-Pool | Storage-Pool 


| Nutanix Container | Internes Volumen 


| Nutanix Container | Dateifreigabe 


| NFS-Share | Share 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Die IP-Adresse für externe Datendienste für den Cluster
* Schreibgeschützter Benutzername und Kennwort, sofern keine Volume_groups verwendet werden, sind in diesem Fall Administratorbenutzername und Passwort erforderlich
* Port-Anforderung: HTTPS 443




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Externe IP-Adresse des Prism | Die IP-Adresse für externe Datendienste für den Cluster 


| Benutzername | Benutzername für das Administratorkonto 


| Passwort | Kennwort für das Administratorkonto 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP Port für die Verbindung mit dem Nutanix Array. Der Standardwert ist 9440. 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 60 Minuten. 


| Abfrageintervall (Sek.) | Intervall zwischen Performance-Abstimmungen Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
