---
sidebar: sidebar 
permalink: task_create_application.html 
summary: Sie erstellen Anmerkungsregeln, mit denen Anmerkungen automatisch auf mehrere Assets angewendet werden können, basierend auf den von Ihnen definierten Kriterien. 
keywords: application, create application, 
---
= Anwendungen Werden Erstellt
:allow-uri-read: 


[role="lead"]
Um die Daten zu verfolgen, die mit bestimmten Applikationen verknüpft sind, die in Ihrer Umgebung ausgeführt werden, können Sie die Applikationen in Cloud Insights definieren.

.Bevor Sie beginnen
Wenn Sie die Anwendung einer Geschäftseinheit zuordnen möchten, müssen Sie die Geschäftseinheit erstellen, bevor Sie die Anwendung definieren.

.Über diese Aufgabe
Mit Cloud Insights können Sie Daten von Ressourcen, die zu Applikationen zugeordnet sind, aus z. B. zu Nutzungsdaten oder zur Kostenberichterstellung nachverfolgen.

.Schritte
. Klicken Sie im Menü Cloud Insights auf *Verwalten > Anwendungen*.

+ das Dialogfeld Anwendung hinzufügen wird angezeigt.

. Geben Sie einen eindeutigen Namen für die Anwendung ein.
. Wählen Sie eine Priorität für die Anwendung aus.
. Klicken Sie Auf *Speichern*.


.Nachdem Sie fertig sind
Nach dem Definieren einer Anwendung kann sie Assets zugewiesen werden.



== Zuweisen von Anwendungen zu Assets

Diese Prozedur weist die Anwendung einem Host als Beispiel zu. Sie können einer Applikation Host, Virtual Machine, Volume oder interne Volumes zuweisen.

.Schritte
. Suchen Sie das Asset, dem Sie der Anwendung zuweisen möchten:
. Klicken Sie auf *Abfragen > +Neue Abfrage* und suchen Sie nach Host.
. Klicken Sie auf das Kontrollkästchen links neben dem Host, den Sie der Anwendung zuordnen möchten.
. Klicken Sie Auf *Massenaktionen > Anwendung Hinzufügen*.
. Wählen Sie die Anwendung aus, der Sie die Anlage zuweisen.


.Nachdem Sie fertig sind
Nachdem Sie den Host der Anwendung zugewiesen haben, können Sie die verbleibenden Assets der Anwendung zuweisen. Um auf die Landing Page für die Anwendung zuzugreifen, klicken Sie auf *Verwalten > Anwendung* und wählen Sie die von Ihnen erstellte Anwendung aus.
