---
sidebar: sidebar 
permalink: task_dc_ibm_cs.html 
keywords: data collector, IBM CS, CS Series 
summary: IBM CS Data Collector wird konfiguriert. 
---
= IBM CS Datensammler
:allow-uri-read: 


[role="lead"]
Cloud Insights verwendet diese Datensammlung, um Bestands- und Performance-Daten für IBM CS Storage-Systeme zu ermitteln.



== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen vom IBM CS Datensammler. Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Storage-Pool | Storage-Pool 


| Container | Internes Volumen 


| Container | Dateifreigabe 


| NFS-Share | Share 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Die IP-Adresse für externe Datendienste für den Cluster
* Administrator-Benutzername und -Passwort
* Port 9440




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Externe IP-Adresse des Prism | Die IP-Adresse für externe Datendienste für den Cluster 


| Benutzername | Benutzername für das Administratorkonto 


| Passwort | Kennwort für das Administratorkonto 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port, der für die Verbindung mit dem IBM CS-Array verwendet wird. Der Standardwert ist 9440. 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 60 Minuten. 


| Abfrageintervall (Sek.) | Intervall zwischen Performance-Abstimmungen Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
