---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: ECS-Datensammler konfigurieren. 
---
= Konfigurieren des EMC ECS-Datensammlers
:allow-uri-read: 


[role="lead"]
Dieser Datensammler erfasst Bestands- und Performancedaten von EMC ECS Speichersystemen. Zur Konfiguration benötigt der Datensammler eine IP-Adresse des ECS-Servers und ein Domain-Konto auf Administratorebene.



== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen vom ECS Datensammler. Für jeden erfassten Asset-Typ wird die am häufigsten für dieses Dokument verwendete Terminologie angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Cluster | Storage 


| Mandant | Storage-Pool 


| Eimer | Internes Volumen 


| Festplatte | Festplatte 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. Diese stellen für diesen Datensammler möglicherweise nicht alle Fälle dar.



== Anforderungen

* Eine IP-Adresse der ECS Management Console
* Domain-Konto auf Administratorebene für das ECS-System
* Port 443 (HTTPS): Erfordert eine ausgehende Verbindung zum TCP-Port 443 des ECS-Systems.
* Für die Leistung können Sie den schreibgeschützten Benutzernamen und das Kennwort für den ssh/scp-Zugriff verwenden.
* Für die Leistung ist Port 22 erforderlich.




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| ECS Host | IP-Adresse oder vollqualifizierter Domain-Name des ECS-Systems 


| ECS-Host-Port | Port, der für die Kommunikation mit ECS Host verwendet wird 


| ECS Anbieter-ID | Anbieter-ID für ECS 


| Passwort | Passwort wird für ECS verwendet 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Der Standardwert ist 360 Minuten. 
|===


== Fehlerbehebung

Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
