---
sidebar: sidebar 
permalink: task_config_telegraf_dcos.html 
keywords: telegraf, installation, install, dcos 
summary: dcos-Konfiguration 
---
= DC/OS Data Collector
:allow-uri-read: 


[role="lead"]
Cloud Insights verwendet diese Datenerfassung zum Erfassen von Kennzahlen aus DC/OS.



== Installation

. Klicken Sie in *Admin > Data Collectors* auf *+Data Collector*. Wählen Sie unter *Services* *DC/OS*.
+
Wenn Sie keinen Agenten für die Sammlung konfiguriert haben, werden Sie aufgefordert link:task_config_telegraf_agent.html["Installieren Sie einen Agenten"] Ihrer Umgebung zu unterstützen.

+
Wenn Sie bereits einen Agenten konfiguriert haben, wählen Sie das entsprechende Betriebssystem oder die entsprechende Plattform aus, und klicken Sie auf *Weiter*.

. Befolgen Sie die Anweisungen im Bildschirm DC/OS-Konfiguration, um den Datensammler zu konfigurieren. Die Anweisungen hängen vom Betriebssystem oder der Plattform ab, die Sie zur Datenerfassung verwenden.




== Einrichtung

Informationen zur Einrichtung finden Sie im https://docs.mesosphere.com["DC/OS-Dokumentation"].



== Objekte und Zähler

Folgende Objekte und ihre Zähler werden gesammelt:

[cols="<.<,<.<,<.<,<.<"]
|===
| Objekt | Identifikatoren | Merkmale | Datenpunkte 


| dcos_Node | dcos_Container dcos_App | Cluster-Hostname-Pfad (nur Filesystem-Felder) Schnittstelle (nur Netzwerkfelder) Container_id Task_Name | System_Uptime (float) cpu_Cores (float) cpu_total (float) cpu_user (float) cpu_System (float) cpu_inle (float) cpu_wait (float) load_1min (float) load_buat) CPU_adyed_fat (Byte) (inode_convered_fat_Network) (inode_ady2_ady2_Byte) (inode_Network) (inode_adytes) (Byte)) (Byte_Byte_Byte_inode_Network) (inode_inode_out_Byte) (inode_Byte_out_Byte_Byte) (inode_Byte) (inde_Network) (Byte)) (inode_adym_adytes_adym_inode_adym_adym_inode_out_adym_out_adym_adym_adym Network_in_Packets (float) Network_out_Packets (float) Network_in_Drop (float) Network_out_Drop (float) Network_in_errors (float) Network_out_errors (float) Process_count (float) 
|===


== Fehlerbehebung

Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Seite.
