---
sidebar: sidebar 
permalink: task_dc_emc_vnxe.html 
keywords: data collector, VNXe, EMC 
summary: VNXe-Datensammler wird konfiguriert. 
---
= Konfigurieren des EMC VNXe-Datensammlers
:allow-uri-read: 


[role="lead"]
DER DELL EMC VNXe Data Collector bietet Bestandsunterstützung für VNXe Unified Storage-Arrays. Cloud Insights unterstützt derzeit iSCSI- und NAS-Protokolle.



== Anforderungen

* Der VNXe-Datensammler ist CLI-basiert. Sie müssen Unisphere for VNXe CLI (uemcli.exe) auf der Erfassungseinheit installieren, in der sich Ihr VNXe-Datensammler befindet.
* uemcli.exe verwendet HTTPS als Transportprotokoll, sodass die Erfassungseinheit in der Lage sein muss, HTTPS-Verbindungen zur VNXe zu initiieren.
* IP-Adresse oder vollqualifizierter Domänenname des VNXe -Geräts
* Sie müssen mindestens einen schreibgeschützten Benutzer zur Verwendung durch den Datensammler haben.
* IP-Adresse des Managing Solutions Enabler Servers.
* HTTPS am Port 443 ist erforderlich
* Der EMC VNXe Data Collector bietet NAS- und iSCSI-Unterstützung für die Inventarisierung. Fibre Channel-Volumes werden erkannt, Cloud Insights erstellt jedoch keine Berichte zu FC-Mapping, Maskierung oder Storage-Ports.




== Terminologie

Cloud Insights erfasst die folgenden Bestandsinformationen vom VNXe-Datensammler. Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieses Datensammlers die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Festplatte | Festplatte 


| Storage Array Durchführt | Storage 


| Prozessor | Storage-Node 


| Storage-Pool | Storage-Pool 


| Allgemeine iSCSI-Block-Informationen, VMware VMFS | Share 


| Remote-Replikationssystem | Synchronisierung 


| ISCSI-Node | ISCSI-Ziel-Node 


| ISCSI-Initiator | ISCSI-Target-Initiator 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. In dieser Datenquelle fallen möglicherweise nicht alle Fälle an.



== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| VNXe-Speicher | IP-Adresse oder vollqualifizierter Domänenname des VNXe -Geräts 


| Benutzername | Benutzername für das VNXe-Gerät 


| Passwort | Kennwort für das VNXe -Gerät 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 40 Minuten 


| CLI-Port | Port, der für die VNXe-CLI verwendet wird 


| Leistungsintervall (Sek.) | Der Standardwert ist 300. 
|===


== Fehlerbehebung

Einige Dinge zu versuchen, wenn Sie Probleme mit diesem Datensammler stoßen:



==== Inventar

[cols="2*"]
|===
| Problem: | Versuchen Sie dies: 


| „Externes Dienstprogramm konnte nicht ausgeführt werden“ mit Fehlermeldungen „Unisphere executable uemcli konnte nicht gefunden werden“ | * Überprüfen Sie die korrekte IP-Adresse, den Benutzernamen und das Kennwort * Bestätigen Sie, dass Unisphere CLI auf der Cloud Insights-Erfassungseinheit installiert ist * Bestätigen Sie, dass das Installationsverzeichnis der Unisphere CLI in der Datasource-Konfiguration korrekt ist. * Bestätigen Sie, dass die IP-Adresse der VNXe in der Konfiguration der Datenquelle korrekt ist. Öffnen Sie in der Cloud Insights Acquisition Unit einen CMD, und wechseln Sie in das konfigurierte Installationsverzeichnis: €{INSTALLDIR. Versuchen Sie, eine Verbindung zum VNXe-Gerät herzustellen, indem Sie Folgendes eingeben: Uemcli -d <Ihre IP> -U <Ihre ID> /sys/General show 
|===
Weitere Informationen finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
