---
sidebar: sidebar 
permalink: task-moving-resource-groups-azure.html 
keywords: move resource groups, azure, remove working environment, resource groups, azure console, Azure subscriptions 
summary: Cloud Volumes ONTAP unterstützt Azure Ressourcengruppen. Der Workflow wird jedoch nur in der Azure Konsole ausgeführt. 
---
= Verschieben von Ressourcengruppen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP unterstützt Azure Ressourcengruppen. Der Workflow wird jedoch nur in der Azure Konsole ausgeführt.

Sie können eine Arbeitsumgebung innerhalb eines Azure-Abonnements von einer Ressourcengruppe auf eine andere Ressourcengruppe in Azure verschieben. Das Verschieben von Ressourcengruppen zwischen verschiedenen Azure-Abonnements wird nicht unterstützt.

.Schritte
. Entfernen Sie die Arbeitsumgebung aus *Canvas*.
+
Informationen zum Entfernen einer Arbeitsumgebung finden Sie unter link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-removing.html["Entfernen von Cloud Volumes ONTAP Arbeitsumgebungen"].

. Führen Sie die Verschiebung der Ressourcengruppe in der Azure-Konsole aus.
+
Informationen zum Abschließen des Verzuvöllig finden Sie unter link:https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription["Verschieben Sie Ressourcen in eine neue Ressourcengruppe oder ein Abonnement in der Microsoft Azure-Dokumentation"^].

. Entdecken Sie in *Canvas* die Arbeitsumgebung.
. Suchen Sie in den Informationen für die Arbeitsumgebung nach der neuen Ressourcengruppe.


.Ergebnis
Die Arbeitsumgebung und ihre Ressourcen (VMs, Festplatten, Speicherkonten, Netzwerkschnittstellen, Snapshots) befinden sich in der neuen Ressourcengruppe.
