---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: Konfigurieren des XtremeIO-Datensammlers. 
---
= Dell EMC XtremeIO-Datensammler
:allow-uri-read: 


[role="lead"]
Der EMC XtremIO Data Collector erwirbt Bestands- und Performance-Daten vom EMC XtremIO Storage-System.



== Anforderungen

Zum Konfigurieren des EMC XtremIO (HTTP) Datensammlers sind folgende Funktionen erforderlich:

* Die Host-Adresse des XtremIO Management Servers (XMS)
* Ein Konto mit Administratorrechten
* Zugriff auf Port 443 (HTTPS)




== Terminologie

Cloud Insights erwirbt die folgenden Bestandsinformationen vom EMC XtremIO Data Collector. Die am häufigsten für diese Ressource verwendete Terminologie wird für jeden von Cloud Insights erfassten Asset-Typ angezeigt. Beachten Sie bei der Anzeige oder Fehlerbehebung dieser Datenquelle die folgende Terminologie:

[cols="2*"]
|===
| Anbieter-/Modelllaufzeit | Laufzeit Für Cloud Insights 


| Festplatte (SSD) | Festplatte 


| Cluster | Storage 


| Controller | Storage-Node 


| Datenmenge | Datenmenge 


| LUN-Zuordnung | Volume-Zuordnung 


| Ziel-FC-Initiator | Volume-Maske 
|===
Hinweis: Es handelt sich hierbei nur um allgemeine Terminologiezuordnungen. In dieser Datenquelle fallen möglicherweise nicht alle Fälle an.



== Anforderungen

* Die XMS-Host-IP-Adresse des XtremIO Management Servers (XMS)
* Administratorbenutzername und -Passwort für den XtremIO




== Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| XMS-Host | IP-Adresse oder vollqualifizierter Domain-Name des XtremIO Management Servers 


| Benutzername | Benutzername für den XtremIO Management Server 


| Passwort | Passwort für den XtremIO Management Server 
|===


== Erweiterte Konfiguration

[cols="2*"]
|===
| Feld | Beschreibung 


| TCP-Port | TCP-Port für die Verbindung mit dem XtremIO Management Server. Der Standardwert ist 443. 


| Abfrageintervall für Bestand (min) | Intervall zwischen Bestandsabstimmungen Der Standardwert ist 60 Minuten. 


| Leistungsintervall (Sek.) | Intervall zwischen Performance-Abstimmungen Der Standardwert beträgt 300 Sekunden. 
|===


== Fehlerbehebung

Weitere Informationen zu diesem Data Collector finden Sie im link:concept_requesting_support.html["Unterstützung"] Oder auf der link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector Supportmatrix"].
